set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})
include(GetGitRevisionDescription)
include(VCMIUtils)
get_git_head_revision(GIT_REFSPEC GIT_SHA1)
set(GIT_BRANCH "${GIT_REFSPEC}")
string(REPLACE "refs/heads/" ""   GIT_BRANCH "${GIT_BRANCH}")
string(REPLACE "refs/remotes/" "" GIT_BRANCH "${GIT_BRANCH}")
string(REPLACE "origin/" ""       GIT_BRANCH "${GIT_BRANCH}")
if(NOT GIT_BRANCH STREQUAL "beta" AND NOT GIT_BRANCH STREQUAL "develop" AND NOT GIT_BRANCH STREQUAL "master")
    set(GIT_BRANCH "")
endif()
configure_file("${CMAKE_CURRENT_LIST_DIR}/../Version.cpp.in" "Version.cpp" @ONLY)
vcmi_print_git_commit_hash()
