Subsystem sftp internal-sftp

# uploader: only sftp access
Match User uploader
    ForceCommand internal-sftp
    ChrootDirectory /home/uploader
    PermitTTY no
    AllowAgentForwarding no
    AllowTcpForwarding no
    X11Forwarding no
    PermitUserRC no
