Document: vcmi
Title: Debian vcmi Manual
Author: <insert document author here>
Abstract: This manual describes what vcmi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vcmi/vcmi.sgml.gz

Format: postscript
Files: /usr/share/doc/vcmi/vcmi.ps.gz

Format: text
Files: /usr/share/doc/vcmi/vcmi.text.gz

Format: HTML
Index: /usr/share/doc/vcmi/html/index.html
Files: /usr/share/doc/vcmi/html/*.html
