---@meta
-- Auto-generated Lua Language Server definitions for the VCMI scripting API.
-- Generated by `vcmiserver --export-lua-docs`. Do not edit by hand.

---A static artifact definition from the game database. Identifies an artifact kind; concrete instances worn by heroes are a separate concept not currently exposed to scripts.
---@class Artifact
local Artifact = {}

---Returns the JSON key (mod-scoped identifier) of this entity.
---@return string
function Artifact:getJsonKey() end

---True if the artifact occupies the 'big' artifact slot (cannot be carried in the backpack).
---@return boolean
function Artifact:isBig() end

---True if the artifact can be traded between heroes or sold at the marketplace.
---@return boolean
function Artifact:isTradable() end

---Returns the artifact's gold value.
---@return integer
function Artifact:getPrice() end

---Battlefield query interface. The handle scripts receive whenever they are passed a battle context — enumerate units and obstacles, test hex accessibility and shooting penalties, inspect wall state on siege maps. Read-only; mutations go through Server.
---@class Battle
local Battle = {}

---Returns the available tactic phase distance, or 0 if the tactic phase has ended.
---@return integer
function Battle:getTacticDistance() end

---Returns an empty hex next to desired location that the creature can be placed on.
---@param creature Creature # Creature template whose footprint is being placed.
---@param side BattleSide # Side whose deployment area to search.
---@param hex BattleHex? # Preferred origin hex; nil falls back to a side-appropriate default.
---@return BattleHex # Empty hex closest to the desired location that fits the creature, or INVALID if none.
function Battle:getAvailableHex(creature, side, hex) end

---Returns all units for which the predicate returns true.
---@param predicate fun(u: Unit): boolean # Selector — called for each unit on the battlefield; unit is kept when it returns true.
---@return Unit[] # Units for which the predicate returned true.
function Battle:getUnitsIf(predicate) end

---True if the given hex is reachable by the given unit either on current turn or on any future turns.
---@param unit Unit # Unit whose movement model is consulted.
---@param hex BattleHex # Hex to test for reachability.
---@return boolean
function Battle:isAccessibleForUnit(unit, hex) end

---True if a ranged attack along this line crosses a wall or moat (per the flags).
---@param from BattleHex # Origin hex of the ranged attack.
---@param dest BattleHex # Target hex of the ranged attack.
---@param checkWall boolean # Pass true to count crossing a wall as a penalty source.
---@param checkMoat boolean # Pass true to count crossing a moat as a penalty source.
---@return boolean
function Battle:hasPenaltyOnLine(from, dest, checkWall, checkMoat) end

---Returns the unit covering the given hex, or nil.
---@param hex BattleHex # Hex to inspect for a unit.
---@param onlyAlive boolean # Pass true to skip dead-but-resurrectable stacks.
---@return Unit
function Battle:getUnitByPos(hex, onlyAlive) end

---Returns all obstacles on the battlefield.
---@return Obstacle[]
function Battle:getAllObstacles() end

---Returns the obstacles on the given hex.
---@param hex BattleHex # Hex whose obstacles are queried.
---@param onlyBlocking boolean # Pass true to limit results to obstacles that block movement.
---@return Obstacle[]
function Battle:getObstaclesOnPos(hex, onlyBlocking) end

---True if the battle is a siege with fortifications present.
---@return boolean
function Battle:hasFortifications() end

---True if the battlefield has a moat.
---@return boolean
function Battle:hasMoat() end

---True if the given side has at least one native-terrain stack.
---@param side BattleSide # Battle side to inspect (attacker or defender).
---@return boolean
function Battle:hasNativeStack(side) end

---Returns every valid battlefield hex.
---@return BattleHexArray
function Battle:getAllPossibleHexes() end

---Returns the current state of the given wall section, or nil if absent.
---@param part WallPart # Wall section to query.
---@return integer?
function Battle:getWallState(part) end

---True if the given wall section can be targeted by an attack.
---@param part WallPart # Wall section to test.
---@return boolean
function Battle:isWallPartAttackable(part) end

---Returns the battle hex corresponding to the given wall section.
---@param part WallPart # Wall section to look up.
---@return BattleHex
function Battle:wallPartToBattleHex(part) end

---Returns the wall section corresponding to the given battle hex.
---@param hex BattleHex # Hex to look up.
---@return WallPart
function Battle:hexToWallPart(hex) end

---Returns the hex used by the tower shooter for the given wall section.
---@param part WallPart # Wall section whose tower-shooter hex is queried.
---@return BattleHex
function Battle:getTowerShooterHex(part) end

---Represents a single tile on the battlefield gridallows computing geometric relationships (distance, neighbours, line-of-sight) that don't rely on current state of a battlefield
---@class BattleHex
local BattleHex = {}

---Returns true if this hex value identifies existing battlefield position.
---@return boolean
function BattleHex:isValid() end

---Returns true if the hex is on the battlefield and is not located in the first or last column, which are reserved for back tile of war machines and are not accessible for regular movement. NOTE: does NOT checks whether hex is blocked by obstacles or units
---@return boolean
function BattleHex:isAvailable() end

---Searches provided array for hex that is closest to current one. If multiple equidistant hexes are found, this function will prefer hex closest to specified battle side.
---@param side BattleSide # Tie-breaker side — closer to this side wins when several candidates are equidistant.
---@param hexes BattleHexArray # Candidate hexes to search through.
---@return BattleHex
function BattleHex:getClosestTile(side, hexes) end

---Returns the neighbouring hex one step north-west.
---@return BattleHex
function BattleHex:copyToNorthWest() end

---Returns the neighbouring hex one step north-east.
---@return BattleHex
function BattleHex:copyToNorthEast() end

---Returns the neighbouring hex one step east.
---@return BattleHex
function BattleHex:copyToEast() end

---Returns the neighbouring hex one step south-east.
---@return BattleHex
function BattleHex:copyToSouthEast() end

---Returns the neighbouring hex one step south-west.
---@return BattleHex
function BattleHex:copyToSouthWest() end

---Returns the neighbouring hex one step west.
---@return BattleHex
function BattleHex:copyToWest() end

---A list of BattleHex values. Used wherever the engine returns or accepts a set of tiles (reachable hexes, area-of-effect, obstacle footprint, …). Supports indexed access, insertion, and erasure; iteration order matches insertion order
---@class BattleHexArray
local BattleHexArray = {}

---Adds the given hex to the list (no-op if already present).
---@param hex BattleHex # Hex to insert.
function BattleHexArray:insert(hex) end

---Removes the given hex from the list (no-op if absent).
---@param hex BattleHex # Hex to remove.
function BattleHexArray:erase(hex) end

---True if the list contains the given hex.
---@param hex BattleHex # Hex to test for membership.
---@return boolean
function BattleHexArray:contains(hex) end

---Returns the number of unique hexes stored in the list.
---@return integer
function BattleHexArray:size() end

---Returns the hex at the given 1-based index.
---@param index integer # 1-based position of the hex to fetch.
---@return BattleHex
function BattleHexArray:at(index) end

---A single effect contributing to target abilities (e.g. +5 attack, immunity to fire spells). Carries type, value, source, duration, stacking key. Scripts read bonuses through `getBonuses(...)` and construct new ones via addUnitBonus or addBattleBonus in ServerCallback.
---@class Bonus
local Bonus = {}

---Returns the bonus type as its JSON key.
---@return string
function Bonus:getType() end

---Returns the integer magnitude of the bonus.
---@return integer
function Bonus:getVal() end

---Returns the bonus subtype as a JSON key (the meaning depends on getType).
---@return string
function Bonus:getSubtype() end

---Returns the JSON key identifying the entity that granted this bonus.
---@return string
function Bonus:getSourceID() end

---Returns the source category (artifact, creature ability, spell, ...) of the bonus.
---@return BonusSource
function Bonus:getSource() end

---Returns the list of duration flags currently set on the bonus.
---@return BonusDuration[]
function Bonus:getDuration() end

---Returns how the value combines with other bonuses (additive, percent, base number, ...).
---@return BonusValueType
function Bonus:getValType() end

---Returns the stacking key — bonuses with the same key from the same source do not stack.
---@return string
function Bonus:getStacking() end

---Returns the remaining turns until the bonus expires (0 if not turn-limited, only active if duration is set accordingly).
---@return integer
function Bonus:getTurnsRemain() end

---True if the bonus is hidden from the player's interface display.
---@return boolean
function Bonus:isHidden() end

---Returns the bonus's extra parameters encoded as a single integer (0 if none).
---@return integer
function Bonus:getParametersAsNumber() end

---Configuration for a Bonus that scripts hand to ServerCallback `addUnitBonus` or `addBattleBonus`. Fields mirror the JSON bonus definition. See bonus docs for more details.
---@class BonusDescriptor
---@field val integer # Numeric magnitude of the bonus (interpreted per `valueType`).
---@field turns integer # Remaining duration in turns; relevant for the N_TURNS / N_DAYS durations.
---@field hidden boolean # If true, the bonus is not shown in the unit's bonus list UI.
---@field stacking string # Stacking key — bonuses sharing it overwrite rather than accumulate.
---@field description string # Optional human-readable description (used by tooltips when shown). Overrides generic description for this bonus type.
---@field icon string # Optional icon name shown next to the bonus in the UI. Overrides generic icon for this bonus type.
---@field type any # Bonus type name (e.g. "PRIMARY_SKILL", "FIRE_IMMUNITY"). See Bonus types documentation.
---@field subtype any # Sub-selector that narrows the type (e.g. specific creature, school, primary stat).
---@field valueType any # How `val` is combined with other bonuses: additive, base, percent-of-..., independent min/max.
---@field effectRange any # Spatial scope the bonus applies in (e.g. ranged-only or melee-only).
---@field duration any # When the bonus expires — permanent, one-battle, n-turns, until-attacked, etc.
---@field sourceType any # Origin class (artifact, spell effect, secondary skill, …) — drives source-based dispels.
---@field sourceID any # Identifier of the specific source within its sourceType.
---@field targetSourceType any # Source type the bonus is restricted to act upon (used by hero specialty bonuses).
---@field addInfo any # Optional auxiliary payload — meaning depends on the bonus type.
---@field limiters any # JSON-defined limiter chain that definea whether the bonus applies to a given bearer.
---@field propagator any # Rule for propagating the bonus upwards for area effect (army-wide, player-wide, …).
---@field updater any # Rules for recalculation of bonus parameters (e.g. scales with stack count).
---@field propagationUpdater any # Updater applied to bonuses produced by this one's propagator.
local BonusDescriptor = {}

---A collection of Bonus values returned by `getBonuses(...)`. Use `size()` and `getBonus(index)` to iterate. A copy of the engine's internal list at the moment of the call — changes to holder afterwards will not affect this snapshot.
---@class BonusList
local BonusList = {}

---Returns the number of bonuses in this list.
---@return integer
function BonusList:size() end

---Returns the bonus at the given 1-based index. Throws if the index is out of range.
---@param index integer # 1-based position of the bonus to fetch.
---@return Bonus # Bonus stored at the given position.
function BonusList:getBonus(index) end

---A creature type from the database (e.g. "pikeman"). Carries base stats, faction, recruitment cost, and the bonuses every instance starts with. Concrete battlefield or army-slot instances are Unit and StackInstance respectively.
---@class Creature
local Creature = {}

---Returns the JSON key (mod-scoped identifier) of this entity.
---@return string
function Creature:getJsonKey() end

---Returns the base maximum hit points of a single creature of this type. Equivalent to getBaseHitPoints.
---@return integer
function Creature:getMaxHealth() end

---Select either the singular or plural text ID for the requested amount.
---@param amount integer # Stack size; passes through to the singular form when equal to 1, plural otherwise.
---@return string
function Creature:getNameTextID(amount) end

---Returns the minimum stack size for this creature when generated on the adventure map.
---@return integer
function Creature:getMapAmountMin() end

---Returns the maximum stack size for this creature when generated on the adventure map.
---@return integer
function Creature:getMapAmountMax() end

---Returns the AI value used for army strength calculations.
---@return integer
function Creature:getAIValue() end

---Returns the combat power value of one creature of this type.
---@return integer
function Creature:getFightValue() end

---Returns the creature level, usually in (1..7) range.
---@return integer
function Creature:getLevel() end

---Returns the base weekly growth rate for this creature in town dwellings.
---@return integer
function Creature:getGrowth() end

---Returns the extra growth granted by the horde building (0 if none).
---@return integer
function Creature:getHorde() end

---Returns the recruitment cost in the specified resource.
---@param resourceID integer # JSON key of the resource whose cost is being queried (e.g. `gold`, `ore`).
---@return integer
function Creature:getRecruitCost(resourceID) end

---True if the creature occupies two hexes on the battlefield.
---@return boolean
function Creature:isDoubleWide() end

---The global `ENUM` table — string->integer constants scripts use to avoid magic numbers. Each field below is a named group; the runtime value is a Lua table whose keys are the constant names.
---@class Enums
---@field HealLevel HealLevel # Outcome categories for the heal action: plain heal / resurrect / overheal.
---@field HealPower HealPower # Persistence of healing effects: one-battle vs permanent.
---@field SpellCastProblem SpellCastProblem # Error codes returned from spell-cast validation.
---@field AimType AimType # Targeting modes a spell can require: none, creature, obstacle, location.
---@field BonusDuration BonusDuration # Lifetime selectors used by Bonus / BonusDescriptor `duration`.
---@field BonusSource BonusSource # Origin classes used by Bonus / BonusDescriptor `sourceType`.
---@field BonusValueType BonusValueType # Combination rules used by Bonus / BonusDescriptor `valueType`.
---@field ObstacleType ObstacleType # Obstacle categories used by SpellObstacleDescriptor `obstacleType`.
---@field WallPart WallPart # Town-wall sections referenced by siege APIs and `catapultAttack`.
---@field BattleSide BattleSide # Battlefield side identifiers: none / attacker / defender.
local Enums = {}

---Outcome categories for the heal action: plain heal / resurrect / overheal.
---@enum HealLevel
local HealLevel = {
    ---Standard healing — capped at the stack's current size, does not revive dead.
    heal = 0,
    ---Brings dead creatures in the stack back, up to the starting count.
    resurrect = 1,
    ---Allows increasing size of stack past the starting count.
    overheal = 2,
}

---Persistence of healing effects: one-battle vs permanent.
---@enum HealPower
local HealPower = {
    ---Resurrected troops disapper when the battle ends.
    oneBattle = 0,
    ---Resurrected troops persist into the post-battle stack state.
    permanent = 1,
}

---Error codes returned from spell-cast validation.
---@enum SpellCastProblem
local SpellCastProblem = {
    ---There is no hero available to cast the spell.
    noHeroToCastSpell = 1,
    ---The caster has already used their per-turn cast allowance.
    castsPerTurnLimit = 2,
    ---The caster does not carry a spellbook.
    noSpellbook = 3,
    ---The spell is not present in the caster's spellbook.
    heroDoesntKnowSpell = 4,
    ---The caster does not have enough mana for this spell.
    notEnoughMana = 5,
    ---An adventure-map spell was attempted in battle context.
    advmapSpellInsteadOfBattleSpell = 6,
    ---The caster's wisdom is too low for the spell's level.
    spellLevelLimitExceeded = 7,
    ---Dispel was cast but there are no eligible spells to remove.
    noSpellsToDispel = 8,
    ---No legal target was selected for the spell.
    noAppropriateTarget = 9,
    ---The chosen target unit is immune to this spell.
    stackImmuneToSpell = 10,
    ---The selected target is not valid for this spell's AimType.
    wrongSpellTarget = 11,
    ---Spells may not be cast during the tactic phase.
    ongoinTacticPhase = 12,
    ---Magic is suppressed on this battlefield (anti-magic terrain or effect).
    magicIsBlocked = 13,
}

---Targeting modes a spell can require: none, creature, obstacle, location.
---@enum AimType
local AimType = {
    ---Spell takes no target - massive spells that cast directly when selected.
    nothing = 0,
    ---Spell targets one or more units on the battlefield.
    creature = 1,
    ---Spell targets an existing obstacle.
    obstacle = 2,
    ---Spell targets one or more battlefield hexes (no unit required).
    location = 3,
}

---Lifetime selectors used by Bonus / BonusDescriptor `duration`.
---@enum BonusDuration
local BonusDuration = {
    ---Lasts forever (until explicitly removed).
    permanent = 1,
    ---Expires at the end of the current battle.
    oneBattle = 2,
    ---Expires after end of current in-game day.
    oneDay = 4,
    ---Expires after end of current in-game week.
    oneWeek = 8,
    ---Expires after N battle turns.
    nTurns = 16,
    ---Expires after N in-game days.
    nDays = 32,
    ---Expires the first time the bearer is attacked.
    untilBeingAttacked = 64,
    ---Expires the first time the bearer makes any attack.
    untilAttack = 128,
    ---Expires when the bearer's unit gets to act.
    stackGetsTurn = 256,
    ---Tied to a commander — expires when the commander dies.
    commanderKilled = 512,
    ---Expires when the bearer initiates an attack (not counter-attack).
    untilOwnAttack = 1024,
    ---Expires when the bearer takes spell or environmental damage.
    untilTakingIndirectDamage = 2048,
    ---Expires after the current attack-and-counter sequence resolves.
    untilAfterAttackSequence = 4096,
}

---Origin classes used by Bonus / BonusDescriptor `sourceType`.
---@enum BonusSource
local BonusSource = {
    ---Granted by an artifact definition. Does not stacks if hero has multiple of same artifacts
    artifact = 0,
    ---Granted by a specific equipped artifact instance. Stacks with multiple copies of same artifact
    artifactInstance = 1,
    ---Granted by a map-object type (e.g. Stables).
    objectType = 2,
    ---Granted by a specific instance of map object, stacks with each same object.
    objectInstance = 3,
    ---Innate to the creature type (e.g. dragon breath, undead).
    creatureAbility = 4,
    ---Native-terrain bonus (creature on its faction's home terrain).
    terrainNative = 5,
    ---Battlefield-terrain overlay bonus (magic plains, fiery fields, …).
    terrainOverlay = 6,
    ---Active spell effect on the bearer.
    spellEffect = 7,
    ---Built town structure providing the bonus.
    townStructure = 8,
    ---Hero primary skill (attack/defense/power/knowledge).
    heroBaseSkill = 9,
    ---Hero secondary skill level (Tactics, Offense, Wisdom, …).
    secondarySkill = 10,
    ---Hero specialty (creature affinity, spell affinity, etc.).
    heroSpecial = 11,
    ---Army composition bonus. Currently only used for morale.
    army = 12,
    ---Carry-over bonus from a campaign scenario.
    campaignBonus = 13,
    ---Stack-experience rank bonus.
    stackExperience = 14,
    ---Commander unit ability.
    commander = 15,
    ---Map-wide global effect. Defined in game settings.
    global = 16,
    ---Source not represented by another category.
    other = 17,
}

---Combination rules used by Bonus / BonusDescriptor `valueType`.
---@enum BonusValueType
local BonusValueType = {
    ---Adds to the base value, but after `percent to base`.
    additiveValue = 0,
    ---Adds the base value before any additive/percent steps.
    baseNumber = 1,
    ---Percentage applied to the running total of all sources combined.
    percentToAll = 2,
    ---Percentage applied to the base value only.
    percentToBase = 3,
    ---Percentage applied to the same-source subtotal.
    percentToSource = 4,
    ---Percentage applied only to bonuses from a matching targetSourceType.
    percentToTargetType = 5,
    ---Independent ceiling — wins if greater than the accumulated value.
    independentMax = 6,
    ---Independent floor — wins if smaller than the accumulated value.
    independentMin = 7,
}

---Obstacle categories used by SpellObstacleDescriptor `obstacleType`.
---@enum ObstacleType
local ObstacleType = {
    ---Small, randomly placed battlefield obstacles placed on start of the battle.
    usual = 0,
    ---Large obstacle blocking predefined part of the battlefield. At most one such obstacle is present on map.
    absolute = 1,
    ---Obstacle placed by a spell (Land Mine, Quicksand, Fire Wall, …).
    spellCreated = 2,
    ---Town-siege moat tiles.
    moat = 3,
}

---Town-wall sections referenced by siege APIs and `catapultAttack`.
---@enum WallPart
local WallPart = {
    ---No wall part. Returned for hexes outside the fortifications.
    invalid = -1,
    ---Sections of walls that always exist and always block ranged attacks
    indestructiblePart = -2,
    ---Section of gate that always exists, but does not blocks ranged attacks
    indestructibleGate = -3,
    ---Central keep building, usually built by Citadel.
    keep = 0,
    ---Bottom tower of the town walls, usually built by Castle.
    bottomTower = 1,
    ---Destructible wall segment adjacent to bottom tower.
    bottomWall = 2,
    ---Destructible wall segment immediately below the gatehouse.
    belowGate = 3,
    ---Destructible wall segment immediately above the gatehouse.
    overGate = 4,
    ---Destructible wall segment adjacent to the upper tower.
    upperWall = 5,
    ---Upper tower of the town walls, usually built by Castle.
    upperTower = 6,
    ---Destructible town gate that can only be opened by defenders.
    gate = 7,
}

---Battlefield side identifiers: none / attacker / defender.
---@enum BattleSide
local BattleSide = {
    ---Not associated with any side.
    none = -1,
    ---The attacking army that initiated the battle. Equivalent to `left`
    attacker = 0,
    ---The defending army. Equivalent to `right`
    defender = 1,
    ---Army that starts on the left side of the battlefield. Equivalent to `attacker`.
    left = 0,
    ---Army that starts on the right side of the battlefield. Equivalent to `defender`.
    right = 1,
}

---A town/army faction definition (Castle, Rampart, Inferno, …). Identifies the kind, not a placed town; use Game lookups for the latter.
---@class Faction
local Faction = {}

---Returns the JSON key (mod-scoped identifier) of this entity.
---@return string
function Faction:getJsonKey() end

---True if this faction has town belonging to it in the game. Usually true for all factions other than neutral
---@return boolean
function Faction:hasTown() end

---Adventure-map query interface. Provides world-level lookups: current date, players, towns, heroes, and map objects accessible to the calling script's owner.
---@class Game
local Game = {}

---Returns the hero by its object identifier, or nil if not found.
---@param objectID integer # Map object identifier of the hero to fetch.
---@return HeroInstance
function Game:getHero(objectID) end

---Returns the map object by its identifier, or nil if not found.
---@param objectID integer # Map object identifier of the object to fetch.
---@param verbose boolean # Pass true to log a warning when the object isn't found.
---@return MapObject
function Game:getObj(objectID, verbose) end

---Hero class definition (Knight, Cleric, Ranger, …). Static metadata shared by all heroes of that class; for a placed hero use HeroInstance.
---@class HeroClass
local HeroClass = {}

---Returns the JSON key (mod-scoped identifier) of this entity.
---@return string
function HeroClass:getJsonKey() end

---A hero placed on the adventure map. Provides access to such information as owner, type (Orrin, Kyrre, Astral...), position on map, artifacts, and secondary skills, army composition, primary skills, and all bonuses affecting hero.
---@class HeroInstance
local HeroInstance = {}

---Returns all bonuses affecting the bearer for which the predicate returns true.
---@param predicate fun(b: Bonus): boolean # Selector — called for each bonus on the bearer; bonus is kept when it returns true.
---@return BonusList # Bonuses for which the predicate returned true.
function HeroInstance:getBonuses(predicate) end

---Returns the stack instance in the given army slot, or nil if the slot is empty.
---@param slot integer # Army slot to query (1-based).
---@return StackInstance
function HeroInstance:getStack(slot) end

---Returns the player color that owns this hero.
---@return integer
function HeroInstance:getOwner() end

---Returns the text ID of the hero's name.
---@return string
function HeroInstance:getNameTextID() end

---True if the hero's gender is male.
---@return boolean
function HeroInstance:isMale() end

---True if the hero's gender is female.
---@return boolean
function HeroInstance:isFemale() end

---A specific named hero from the database (Sir Mullich, Crag Hack, …). Identifies the hero kind and their starting profile; the in-game placed hero is HeroInstance.
---@class HeroType
local HeroType = {}

---Returns the JSON key (mod-scoped identifier) of this entity.
---@return string
function HeroType:getJsonKey() end

---Object for constructing strings with translation support. Supports appending text via `append` field and `replaceStrings` / `replaceNumbers` to fill the %s and %d placeholders. Used in all places that expect translatable string with formattingsuch as battle log and spell-problem messages. In case of multiplayer, string is translated on each client according to their language settings
---@class MetaString
---@field append string[] # Sequence of text-ID tokens to concatenate.
---@field replaceStrings string[] # Values that fill %s placeholders in the appended tokens, in order.
---@field replaceNumbers integer[] # Values that fill %d placeholders in the appended tokens, in order.
local MetaString = {}

---A battlefield obstacle (static map decoration, moat tile, or spell-created hazard). Exposed read-only — to add or remove obstacles use the `server:addObstacle` or `server:removeObstacle` methods.
---@class Obstacle
local Obstacle = {}

---Returns the obstacle category: usual, absolute, moat, or spell-created.
---@return ObstacleType
function Obstacle:getObstacleType() end

---Returns the hex that serves as anchor of the obstacle, usually - located in bottom-left corner of the obstacle
---@return BattleHex
function Obstacle:getPosition() end

---Returns the Spell that created this obstacle, or nil for non-spell obstacles.
---@return Spell
function Obstacle:getSpell() end

---The authoritative-side mutation interface. Available only to scripts running on the server: spawn or remove battle units, move them, deal damage, alter bonuses, drop obstacles, append to the combat log, draw from the seeded RNG. Every call emits a network pack so clients receive the resulting state change.
---@class Server
local Server = {}

---Spawns a new battle unit described by the given UnitInfo. Returns the created unit.
---@param battle Battle # Battle in which the unit is created.
---@param info UnitInfo # Descriptor of the unit to spawn (creature type, side, position, ...).
---@return Unit
function Server:addUnit(battle, info) end

---Heals the given unit by the provided amount of health points.
---@param battle Battle # Battle in which the unit is healed.
---@param unit Unit # Target unit.
---@param amount integer # Hit points to restore.
---@param level HealLevel # Heal tier (heal / resurrect / overheal).
---@param power HealPower # Persistence — one-battle vs permanent.
---@return integer, integer # Healed hit points, and the count of creatures resurrected.
function Server:healUnit(battle, unit, amount, level, power) end

---Applies a UnitState mutation to the unit, optionally adjusting current health.
---@param battle Battle # Battle in which the unit is modified.
---@param unitState UnitState # New unit state to apply (returned by `Unit:copy`).
---@param healthDelta integer? # Optional health delta — positive heals, negative damages.
function Server:changeUnit(battle, unitState, healthDelta) end

---Damages the unit, returning the actual damage dealt and the number of killed creatures.
---@param battle Battle # Battle in which damage is dealt.
---@param unit Unit # Target unit.
---@param damage integer # Damage points to deal (will be clamped to remaining health).
---@return integer, integer # Damage actually dealt, and the count of killed creatures.
function Server:damageUnit(battle, unit, damage) end

---Removes the unit or its corpse from the battlefield.
---@param battle Battle # Battle the unit belongs to.
---@param unit Unit # Unit (alive or as corpse) to remove.
function Server:removeUnit(battle, unit) end

---Removes the given obstacle from the battlefield.
---@param battle Battle # Battle the obstacle belongs to.
---@param obstacle Obstacle # Obstacle to remove.
function Server:removeObstacle(battle, obstacle) end

---Moves the unit to the destination hex.
---@param battle Battle # Battle in which the unit is moved.
---@param unit Unit # Unit to move.
---@param destination BattleHex # Target hex of the move.
---@param isTeleport boolean # Pass true to use teleport semantics (no path walk).
function Server:moveUnit(battle, unit, destination, isTeleport) end

---Appends a formatted log entry to the battle log.
---@param battle Battle # Battle whose log is being appended.
---@param message MetaString # Formatted log line (use `MetaString`).
function Server:appendLog(battle, message) end

---Returns whether netpack changes should be described in the battle log.
---@return boolean
function Server:describeChanges() end

---Removes the listed bonuses from the unit.
---@param battle Battle # Battle the unit belongs to.
---@param unit Unit # Unit whose bonuses are removed.
---@param bonusList BonusList # Bonuses to remove from the unit.
function Server:removeUnitBonuses(battle, unit, bonusList) end

---Adds a bonus described by the descriptor to the unit.
---@param battle Battle # Battle the unit belongs to.
---@param unit Unit # Unit to add the bonus to.
---@param descriptor BonusDescriptor # BonusDescriptor that creates the bonus.
---@param cumulative boolean # Pass true to stack with existing same-source bonus, false to update in-place.
function Server:addUnitBonus(battle, unit, descriptor, cumulative) end

---Adds a bonus to the battle-wide bonus set.
---@param battle Battle # Battle to attach the bonus to.
---@param descriptor BonusDescriptor # BonusDescriptor that creates the bonus.
function Server:addBattleBonus(battle, descriptor) end

---Creates a new obstacle described by the descriptor on the battlefield.
---@param battle Battle # Battle the obstacle is placed in.
---@param descriptor SpellObstacleDescriptor # SpellObstacleDescriptor describing the obstacle to create.
function Server:addObstacle(battle, descriptor) end

---Performs a catapult attack against the given wall section, dealing the supplied damage.
---@param battle Battle # Battle in which the catapult attack happens.
---@param attacker Unit # Unit performing the catapult attack.
---@param attackedPart WallPart # Wall section to attack.
---@param damageDealt integer # Damage to apply to the wall section.
function Server:catapultAttack(battle, attacker, attackedPart, damageDealt) end

---Returns a server-side random integer in the inclusive range [low, high].
---@param low integer # Inclusive lower bound.
---@param high integer # Inclusive upper bound.
---@return integer # Random integer in [low, high].
function Server:rngInt(low, high) end

---The static game-content catalogue, bound to the global `LIBRARY`. Looks up artifacts, creatures, factions, hero classes/types, secondary skills and spells by their config name (the same string used in JSON definitions).
---@class Services
local Services = {}

---Looks up an artifact by its JSON key. Returns nil if not found.
---@param name string # JSON key of the artifact (e.g. `core:goldenBow`).
---@return Artifact
function Services:getArtifactByName(name) end

---Looks up a creature by its JSON key. Returns nil if not found.
---@param name string # JSON key of the creature (e.g. `core:pikeman`).
---@return Creature
function Services:getCreatureByName(name) end

---Looks up a faction by its JSON key. Returns nil if not found.
---@param name string # JSON key of the faction (e.g. `core:castle`).
---@return Faction
function Services:getFactionByName(name) end

---Looks up a hero class by its JSON key. Returns nil if not found.
---@param name string # JSON key of the hero class (e.g. `core:knight`).
---@return HeroClass
function Services:getHeroClassByName(name) end

---Looks up a hero type by its JSON key. Returns nil if not found.
---@param name string # JSON key of the hero type (e.g. `core:orrin`).
---@return HeroType
function Services:getHeroTypeByName(name) end

---Looks up a spell by its JSON key. Returns nil if not found.
---@param name string # JSON key of the spell (e.g. `core:magicArrow`).
---@return Spell
function Services:getSpellByName(name) end

---Looks up a secondary skill by its JSON key. Returns nil if not found.
---@param name string # JSON key of the secondary skill (e.g. `core:wisdom`).
---@return Skill
function Services:getSecondarySkillByName(name) end

---Looks up a spell school by its JSON key. Returns nil if not found.
---@param name string # JSON key of the spell school (e.g. `core:fire`).
---@return SpellSchool
function Services:getSpellSchoolByName(name) end

---A secondary-skill definition (Wisdom, Tactics, Logistics, …). Database metadata; per-hero skill levels are read off HeroInstance.
---@class Skill
local Skill = {}

---Returns the JSON key (mod-scoped identifier) of this entity.
---@return string
function Skill:getJsonKey() end

---A spell definition (Fire Bolt, Slow, Town Portal, …). Identifies kind and metadata (schools, level). Cast resolution and per-cast state live on SpellMechanics.
---@class Spell
local Spell = {}

---Returns the JSON key (mod-scoped identifier) of this entity.
---@return string
function Spell:getJsonKey() end

---Returns the text ID of the spell name.
---@return string
function Spell:getNameTextID() end

---True if the spell can only be cast on the adventure map.
---@return boolean
function Spell:isAdventure() end

---True if the spell can only be cast during combat.
---@return boolean
function Spell:isCombat() end

---True if the spell is a creature's innate ability rather than a learnable spell.
---@return boolean
function Spell:isCreatureAbility() end

---True if the spell is classified as beneficial to its target.
---@return boolean
function Spell:isPositive() end

---True if the spell is classified as harmful to its target.
---@return boolean
function Spell:isNegative() end

---True if the spell is classified as neutral (neither positive nor negative).
---@return boolean
function Spell:isNeutral() end

---True if the spell deals direct damage.
---@return boolean
function Spell:isDamage() end

---True if the spell is offensive (damage / curse-type effects).
---@return boolean
function Spell:isOffensive() end

---True if the spell is marked as special (e.g. cannot be obtained from common sources).
---@return boolean
function Spell:isSpecial() end

---True if the spell's effect persists and can't be dispelled normally.
---@return boolean
function Spell:isPersistent() end

---True if the spell is magical in nature (as opposed to a non-magical ability).
---@return boolean
function Spell:isMagical() end

---Returns the mana cost of the spell at the requested skill level.
---@param skillLevel integer # Mastery level used to look up the cost (0=basic, up to 3=expert).
---@return integer
function Spell:getCost(skillLevel) end

---Returns the spell's base power before caster bonuses.
---@return integer
function Spell:getBasePower() end

---Returns the spell's per-level power bonus.
---@param skillLevel integer # Mastery level used to look up the power bonus (0=basic, up to 3=expert).
---@return integer
function Spell:getLevelPower(skillLevel) end

---Returns the list of magic schools the spell belongs to.
---@return SpellSchool[]
function Spell:getSchools() end

---Per-cast spell context: which Spell is being cast, who is casting it, at what power and level. Lua spell scripts receive this as the entry point to their cast logic and consult it for caster identity, target validation, and damage formulas.
---@class SpellMechanics
local SpellMechanics = {}

---True if the spell mechanics classify this cast as a positive effect.
---@return boolean
function SpellMechanics:isPositive() end

---True if the spell mechanics classify this cast as a negative effect.
---@return boolean
function SpellMechanics:isNegative() end

---True if the spell only affects friendly or enemy targets (vs. anyone in range).
---@return boolean
function SpellMechanics:isSmart() end

---True if the spell targets all valid targets simultaneously.
---@return boolean
function SpellMechanics:isMassive() end

---True if the first selected target is always considered hit, ignoring magic resistance.
---@return boolean
function SpellMechanics:alwaysHitFirstTarget() end

---Returns true if the given target would resist this cast.
---@param target Unit # Unit whose resistance is being tested.
---@return boolean
function SpellMechanics:wouldResist(target) end

---Returns the effective mastery level used for the spell's magnitude.
---@return integer
function SpellMechanics:getEffectLevel() end

---Returns the effective mastery level used for the spell's range.
---@return integer
function SpellMechanics:getRangeLevel() end

---Returns the effective spell power applied to the magnitude calculation.
---@return integer
function SpellMechanics:getEffectPower() end

---Returns the effect duration in turns.
---@return integer
function SpellMechanics:getEffectDuration() end

---Returns the computed effect value (e.g. damage / health amount).
---@return integer
function SpellMechanics:getEffectValue() end

---Returns the player color of the caster.
---@return integer
function SpellMechanics:getCasterColor() end

---Returns the battle side of the caster.
---@return BattleSide
function SpellMechanics:getCasterSide() end

---Returns the hero performing the cast, or nil if cast by a unit.
---@return HeroInstance
function SpellMechanics:getHeroCaster() end

---Returns the unit performing the cast, or nil if cast by a hero.
---@return Unit
function SpellMechanics:getUnitCaster() end

---Returns the text ID of the caster's name.
---@return string
function SpellMechanics:getCasterNameTextID() end

---Returns the battle callback associated with this cast.
---@return Battle
function SpellMechanics:getBattle() end

---Returns the raw effect value before unit-specific adjustments.
---@param basePowerMultiplier integer # Multiplier applied to the spell's base power.
---@param levelPowerMultiplier integer # Multiplier applied to the per-level power bonus.
---@return integer
function SpellMechanics:calculateRawEffectValue(basePowerMultiplier, levelPowerMultiplier) end

---Applies any spell-specific bonus modifier and returns the resulting value.
---@param value integer # Base value to which spell-specific modifiers are applied. Use 0 for default
---@return integer
function SpellMechanics:applySpecificSpellBonus(value) end

---Applies the generic spell-damage bonus and returns the resulting value.
---@param value integer # Base value to which the bonus is applied. Use 0 for default.
---@param target Unit # Unit whose own bonuses are factored into the result.
---@return integer
function SpellMechanics:applySpellBonus(value, target) end

---True if the target is receptive (not immune) to the spell.
---@param target Unit # Unit whose receptivity is being checked.
---@return boolean
function SpellMechanics:isReceptive(target) end

---True if the given unit is owned by the same player as the caster.
---@param unit Unit # Unit whose ownership is being compared against the caster's.
---@return boolean
function SpellMechanics:ownerMatches(unit) end

---Returns the Spell being cast.
---@return Spell
function SpellMechanics:getSpell() end

---Applies all per-target adjustments to the raw effect value.
---@param target Unit # Unit against which per-target adjustments are computed.
---@return integer
function SpellMechanics:adjustEffectValue(target) end

---Picks the appropriate plural-form variant of a text ID for the given count and language.
---@param baseTextID string # Base text ID used as the lookup base.
---@param count integer # Count for which engine needs to select plural form.
---@return string
function SpellMechanics:getPluralFormTextID(baseTextID, count) end

---Configuration for a battlefield obstacle that scripts hand to ServerCallback `addObstacle`. Captures anchor position, owning spell, caster stats, behavior flags, presentation assets, and an obstacle hex footprint.
---@class SpellObstacleDescriptor
---@field pos BattleHex # Anchor BattleHex of the obstacle (its primary position). Usually located in bottom-left corner of the obstacle
---@field obstacleType ObstacleType # Obstacle category — usual, absolute, spell-created, moat. See the ObstacleType enum.
---@field spell Spell # Spell that created the obstacle. Used for dispel and damage-source attribution. Only for spell-created obstacles
---@field turnsRemaining integer # How many turns the obstacle persists. -1 means permanent for the battle.
---@field casterSpellPower integer # Spell power of the caster at the moment of creation; feeds damage formulas.
---@field spellLevel integer # Spell skill level (0–3) the obstacle was cast at.
---@field casterSide BattleSide # Which battle side cast it; relevant for native-visibility and friendly-fire rules.
---@field minimalDamage integer # Floor for the damage the obstacle inflicts on trigger.
---@field hidden boolean # If true, the obstacle is invisible to the opposing side until triggered.
---@field passable boolean # If true, units may step onto the obstacle's hexes (e.g. trap obstacles).
---@field trap boolean # If true, behaves as a trap: triggers on enter rather than blocking movement.
---@field removeOnTrigger boolean # If true, the obstacle disappears after being triggered once.
---@field nativeVisible boolean # If true, the caster's side always sees the obstacle even when `hidden` is set.
---@field trigger string # Script-side identifier of the trigger spell (looked up by the spell mechanics).
---@field appearSound string # Sound effect played when the obstacle appears.
---@field appearAnimation string # Animation played when the obstacle appears.
---@field animation string # Looping animation shown while the obstacle is on the battlefield.
---@field customSize BattleHex[] # Optional list of BattleHex values defining a multi-hex footprint.
local SpellObstacleDescriptor = {}

---Output accumulator passed to a spell's `canBeCast` / `canBeCastAt` check. Scripts append reasons the cast cannot proceed — generic, standard (picked from the ESpellCastProblem enum), or fully custom via MetaString. An empty SpellProblem means the cast is allowed.
---@class SpellProblem
local SpellProblem = {}

---Adds a custom-message problem entry built from the given MetaString config.
---@param config MetaString # MetaString that describes the custom problem message.
function SpellProblem:addCustom(config) end

---Adds the generic 'cannot cast' problem entry derived from the given mechanics.
---@param mechanics SpellMechanics # Mechanics of the spell being cast.
function SpellProblem:addGeneric(mechanics) end

---Adds a standard problem entry with the requested SpellCastProblem value.
---@param mechanics SpellMechanics # Mechanics of the spell being cast.
---@param spellProblem SpellCastProblem # Standard problem code to surface.
function SpellProblem:addStandard(mechanics, spellProblem) end

---A spell school (Fire, Water, Earth, Air, …). Identifies which school a spell belongs to and is used for school-based immunity and reduction checks.
---@class SpellSchool
local SpellSchool = {}

---Returns the JSON key (mod-scoped identifier) of this entity.
---@return string
function SpellSchool:getJsonKey() end

---Returns the text ID of the spell school name.
---@return string
function SpellSchool:getNameTextID() end

---A creature stack as it exists in an army outside of combat (hero slot, town garrison, or any other map object). Carries the creature type, current count, and any bonuses it contributes. For the battle-side view of the same stack, see Unit.
---@class StackInstance
local StackInstance = {}

---Returns the Creature type of the units in this stack.
---@return Creature
function StackInstance:getType() end

---Returns the number of creatures currently in this stack.
---@return integer
function StackInstance:getCount() end

---Represents a creature stack participating in the current battle. Provides access to the live combat state — position, owner, current health, applied bonuses, ability checks. To stage modifications, copy into a UnitState, edit it, then commit via server.
---@class Unit
local Unit = {}

---Returns all bonuses affecting the bearer for which the predicate returns true.
---@param predicate fun(b: Bonus): boolean # Selector — called for each bonus on the bearer; bonus is kept when it returns true.
---@return BonusList # Bonuses for which the predicate returned true.
function Unit:getBonuses(predicate) end

---Returns the minimum damage one creature in the stack will deal.
---@param ranged boolean # True for ranged attack value, false for melee.
---@return integer
function Unit:getMinDamage(ranged) end

---Returns the maximum damage one creature in the stack will deal.
---@param ranged boolean # True for ranged attack value, false for melee.
---@return integer
function Unit:getMaxDamage(ranged) end

---Returns the creature's attack stat.
---@param ranged boolean # True for ranged attack value, false for melee.
---@return integer
function Unit:getAttack(ranged) end

---Returns the creature's defense stat.
---@param ranged boolean # True for defense against ranged attacks, false for defense against melee.
---@return integer
function Unit:getDefense(ranged) end

---True if the stack has at least one alive creature.
---@return boolean
function Unit:isAlive() end

---True if this stack is a clone produced by a Clone spell.
---@return boolean
function Unit:isClone() end

---True if this stack has an alive clone summoned by a Clone spell.
---@return boolean
function Unit:hasClone() end

---True if the stack has no remaining alive creatures.
---@return boolean
function Unit:isDead() end

---True if the stack was completely removed from the battlefield including its corpse.
---@return boolean
function Unit:isGhost() end

---True if the stack can be targeted by spells / attacks.
---@param allowDead boolean # Pass true to count dead but resurrectable stacks as valid targets.
---@return boolean
function Unit:isValidTarget(allowDead) end

---True if the stack has invincibility (cannot be damaged or killed).
---@return boolean
function Unit:isInvincible() end

---True if the unit is absolutely immune to the given spell.
---@param spell Spell # Spell to test absolute immunity against.
---@return boolean
function Unit:hasAbsoluteImmunity(spell) end

---True if the stack was summoned during battle (e.g. by Summon Elementals).
---@return boolean
function Unit:isSummoned() end

---Returns the player color controlling this unit.
---@return integer
function Unit:getOwner() end

---Returns the army slot in the army this unit occupies. NOTE: All summoned units share the same slot
---@return integer
function Unit:getSlot() end

---Returns the battle side (attacker or defender) this unit belongs to.
---@return BattleSide
function Unit:unitSide() end

---Returns the battlefield hex occupied by the unit, or front hex for double-wide units
---@return BattleHex
function Unit:getPosition() end

---Returns the total hit points across all creatures in the stack, including dead.
---@return integer
function Unit:getTotalHealth() end

---Returns the current hit points of living creatures of this unit.
---@return integer
function Unit:getAvailableHealth() end

---Returns the number of creatures currently alive in the stack.
---@return integer
function Unit:getCount() end

---Returns the maximum hit points of a single creature in the stack.
---@return integer
function Unit:getMaxHealth() end

---True if the unit currently covers the given hex (accounts for double-wide creatures).
---@param position BattleHex # Battlefield hex to test against the unit's footprint.
---@return boolean
function Unit:coversPos(position) end

---Returns the Creature type of the units in this stack.
---@return Creature
function Unit:getCreature() end

---Returns the initial number of creatures this stack had at battle start.
---@return integer
function Unit:getBaseAmount() end

---Returns the list of hexes currently occupied by the unit.
---@return BattleHexArray
function Unit:getHexes() end

---Returns a copy of the unit's state allowing copying or changing this unit via server calls.
---@return UnitState
function Unit:copy() end

---Returns the creature level (1..7) of the unit's type.
---@return integer
function Unit:creatureLevel() end

---DEPRECATED. Returns the unit's internal numeric identifier.
---@return integer
function Unit:unitID() end

---Editable copy of a battle Unit. Obtained via `Unit:copy()`; scripts edit fields (position, defending, clone, summoned, …) and inflict damage locally, then hand the result to ServerCallback `changeUnit` or `addUnit` to broadcast the update through a battle pack.
---@class UnitState
local UnitState = {}

---Returns the minimum damage one creature will deal.
---@param ranged boolean # True for ranged attack value, false for melee.
---@return integer
function UnitState:getMinDamage(ranged) end

---Returns the maximum damage one creature will deal.
---@param ranged boolean # True for ranged attack value, false for melee.
---@return integer
function UnitState:getMaxDamage(ranged) end

---Returns the creature's attack stat.
---@param ranged boolean # True for ranged attack value, false for melee.
---@return integer
function UnitState:getAttack(ranged) end

---Returns the creature's defense stat.
---@param ranged boolean # True for defense against ranged attacks, false for defense against melee.
---@return integer
function UnitState:getDefense(ranged) end

---True if the stack has at least one alive creature.
---@return boolean
function UnitState:isAlive() end

---True if this stack is a clone produced by the Clone spell.
---@return boolean
function UnitState:isClone() end

---True if the stack has no remaining alive creatures.
---@return boolean
function UnitState:isDead() end

---True if the stack was completely removed from the battlefield including its corpse.
---@return boolean
function UnitState:isGhost() end

---True if the stack can be targeted.
---@param allowDead boolean # Pass true to count dead but resurrectable stacks as valid targets.
---@return boolean
function UnitState:isValidTarget(allowDead) end

---True if the stack has invincibility.
---@return boolean
function UnitState:isInvincible() end

---True if the stack was summoned during battle.
---@return boolean
function UnitState:isSummoned() end

---Returns the player color controlling this unit.
---@return integer
function UnitState:getOwner() end

---Returns the army slot in the army this unit occupies. NOTE: All summoned units share the same slot
---@return integer
function UnitState:getSlot() end

---Returns the battlefield hex occupied by the unit, or front hex for double-wide units
---@return BattleHex
function UnitState:getPosition() end

---Returns the total hit points across all creatures in the stack, including dead.
---@return integer
function UnitState:getTotalHealth() end

---Returns the current hit points of living creatures of this unit.
---@return integer
function UnitState:getAvailableHealth() end

---Returns the number of creatures currently alive in the stack.
---@return integer
function UnitState:getCount() end

---Returns the maximum hit points of a single creature.
---@return integer
function UnitState:getMaxHealth() end

---True if the unit currently covers the given hex.
---@param position BattleHex # Battlefield hex to test against the unit's footprint.
---@return boolean
function UnitState:coversPos(position) end

---Returns the initial number of creatures this stack had at battle start.
---@return integer
function UnitState:getBaseAmount() end

---True if the unit is absolutely immune to the given spell.
---@param spell Spell # Spell to test absolute immunity against.
---@return boolean
function UnitState:hasAbsoluteImmunity(spell) end

---Returns the Creature type of the units in this stack.
---@return Creature
function UnitState:getCreature() end

---Returns the list of hexes currently occupied by the unit.
---@return BattleHexArray
function UnitState:getHexes() end

---Sets whether unit has defended in this round.
---@param value boolean # New defending flag.
function UnitState:setDefending(value) end

---Marks the stack as a clone.
---@param value boolean # New cloned flag.
function UnitState:setCloned(value) end

---Marks that the unit has had drained mana from enemy hero this turn.
---@param value boolean # New drained-mana flag.
function UnitState:setDrainedMana(value) end

---Sets the feared status (skips the unit's current turn).
---@param value boolean # New feared flag — when true the unit will skip its next turn.
function UnitState:setFear(value) end

---Marks that the unit has already triggered a morale bonus this turn.
---@param value boolean # New had-morale flag.
function UnitState:setHadMorale(value) end

---Marks that the unit has cast a spell this turn.
---@param value boolean # New cast-spell-this-turn flag.
function UnitState:setCastSpellThisTurn(value) end

---Sets the ghost state removing them from the battle
---@param value boolean # New ghost flag — when true the unit becomes invisible to the battle.
function UnitState:setGhost(value) end

---Marks the unit as transitioning to the ghost state.
---@param value boolean # New ghost-pending flag.
function UnitState:setGhostPending(value) end

---Marks that the unit has moved this round.
---@param value boolean # New moved-this-round flag.
function UnitState:setMoved(value) end

---Marks the unit as summoned during combat.
---@param value boolean # New summoned flag.
function UnitState:setSummoned(value) end

---Marks that the unit is currently waiting.
---@param value boolean # New waiting flag.
function UnitState:setWaiting(value) end

---Marks that the unit has already used its wait this turn.
---@param value boolean # New waited-this-turn flag.
function UnitState:setWaitedThisTurn(value) end

---Moves the unit to the given hex.
---@param hex BattleHex # Destination hex for the unit.
function UnitState:setPosition(hex) end

---Links this stack to a clone unit produced by a Clone spell.
---@param unit Unit # Unit instance to register as this stack's clone.
function UnitState:setClone(unit) end

---Deals damage to the stack, clamped to available health.
---@param amount integer # Damage to apply; will be clamped to remaining health.
---@return integer # Damage value actually applied (may be less than requested if the stack was killed).
function UnitState:damage(amount) end

---Heals the stack. Returns the healed hit points and the resurrected creature count, if any.
---@param amount integer # Hit points to restore.
---@param level HealLevel # Heal tier (heal, resurrect, overheal).
---@param power HealPower # Persistence — one-battle vs permanent.
---@return integer, integer # Healed hit points, and the count of creatures resurrected (zero if none).
function UnitState:heal(amount, level, power) end

