---@meta
-- Auto-generated Lua Language Server definitions for the VCMI scripting API.
-- Generated by `vcmiserver --export-lua-docs`. Do not edit by hand.

---The authoritative adventure-map mutation interface. Available only to scripts running on the server; every call emits a network pack so clients receive the resulting state change. Grants rewards, shows dialogs, removes map objects and stores script variables.
---@class AdventureServer
local AdventureServer = {}

---Stores a named value that persists in the save file and can be read back later with Game:getMapVariable. Use it to remember progress across visits, such as whether a one-time reward was already handed out.
---@param name string # Name of the variable to store under.
---@param value any # Value to store; any value that survives as JSON - number, string, boolean, or a table of those. Overwrites any previous value.
function AdventureServer:setMapVariable(name, value) end

---Permanently removes a map object from the adventure map. The object disappears for every player; if it was a town or a hero, ownership and garrison are lost as well. There is no undo.
---@param target MapObject # Map object to remove.
function AdventureServer:removeObject(target) end

---Ends the current quest of the given object. A seer hut's active quest is marked complete and cleared, without removing the hut itself; a quest guard is removed from the map. Errors when the object is not a quest source - use removeObject for plain events and pandoras.
---@param target MapObject # The quest source (seer hut / quest guard) that just finished its quest.
function AdventureServer:finishQuestOrRemoveObject(target) end

---Internal plumbing for registerQuest: remembers that a player has already been offered this quest, so a later visit shows the progression text instead of the proposal text again.
---@param target MapObject # The quest source (seer hut / quest guard) to mark.
---@param player integer # Player who has now seen the quest proposed.
function AdventureServer:markQuestProposed(target, player) end

---Adds the object's active quest to a player's in-game quest log. Calling it again for a quest already in the log does nothing.
---@param target MapObject # The quest source (seer hut / quest guard) to add.
---@param player integer # Player whose quest log gains the entry.
function AdventureServer:addToQuestLog(target, player) end

---Internal plumbing for the setQuestHint helper. Scripts should call setQuestHint instead.
---@param target MapObject # The quest source (seer hut / quest guard) whose hint changes.
---@param text MetaString # New hover / quest-log text for the object's active quest.
function AdventureServer:setQuestHintText(target, text) end

---Returns a random whole number in the given range. Draws from the game's own random generator, so the result stays consistent with saved games and network play - do not use Lua's math.random for gameplay decisions.
---@param lower integer # Smallest value that may be returned.
---@param upper integer # Largest value that may be returned.
---@return integer # A whole number between lower and upper, both ends included.
function AdventureServer:random(lower, upper) end

---Awards experience points to a hero, triggering any level-ups (and the level-up dialog for a human player) that result.
---@param hero HeroInstance # Hero that gains the experience.
---@param amount integer # Experience points to add. The hero levels up automatically if the total crosses a level threshold.
function AdventureServer:giveExperience(hero, amount) end

---Adds or removes a single resource for one player.
---@param player integer # Player whose treasury changes.
---@param resource ResourceType # Resource to change, as returned by Services:getResourceByName.
---@param amount integer # How much to add. Use a negative number to take resources away; the treasury is clamped at zero and never goes negative.
function AdventureServer:giveResource(player, resource, amount) end

---Transfers ownership of a map object to another player. For a town or mine this immediately moves its income and control; it does not move any garrisoned army or visiting hero.
---@param object MapObject # Map object whose owner changes, such as a town, mine or dwelling.
---@param owner integer # New owner. Pass the neutral player to make the object unowned.
function AdventureServer:setOwner(object, owner) end

---Teaches a spell to a hero, writing it into the hero's spellbook. The hero needs a spellbook for the spell to be usable in combat. Teaching a spell the hero already knows does nothing.
---@param hero HeroInstance # Hero that learns the spell.
---@param spell Spell # Spell to teach, as returned by Services:getSpellByName.
function AdventureServer:grantSpell(hero, spell) end

---Removes a spell from a hero's spellbook. Does nothing if the hero did not know the spell.
---@param hero HeroInstance # Hero that forgets the spell.
---@param spell Spell # Spell to remove, as returned by Services:getSpellByName.
function AdventureServer:takeSpell(hero, spell) end

---Permanently raises or lowers one of a hero's four primary skills.
---@param hero HeroInstance # Hero whose skill changes.
---@param skill integer # Primary skill to change; use ENUM.PrimarySkill.
---@param amount integer # How many points to add. Use a negative number to reduce the skill; it is clamped at zero and never goes negative.
function AdventureServer:grantPrimarySkill(hero, skill, amount) end

---Teaches a secondary skill to a hero, or changes it to the given mastery. A hero who has no free skill slots left will not learn a brand-new skill.
---@param hero HeroInstance # Hero that learns the skill.
---@param skill Skill # Secondary skill to grant, as returned by Services:getSecondarySkillByName.
---@param level integer # Mastery to move to: 1 = basic, 2 = advanced, 3 = expert.
function AdventureServer:grantSecondarySkill(hero, skill, level) end

---Gives an artifact to a hero. It is equipped in a matching free slot, or placed in the backpack when no suitable slot is free. The hero gains the artifact's bonuses only while it is equipped.
---@param hero HeroInstance # Hero that receives the artifact.
---@param artifact Artifact # Artifact to give, as returned by Services:getArtifactByName.
function AdventureServer:grantArtifact(hero, artifact) end

---Gives a spell scroll to a hero. While the scroll is carried the hero may cast that spell even without a spellbook. The scroll occupies an artifact slot like any other artifact.
---@param hero HeroInstance # Hero that receives the scroll.
---@param spell Spell # Spell written on the scroll, as returned by Services:getSpellByName.
function AdventureServer:grantScroll(hero, spell) end

---Removes an artifact from a hero, whether it is equipped or sitting in the backpack. If the artifact is a part of an assembled combination artifact, the combination is taken apart first and the remaining parts stay with the hero. Does nothing if the hero does not own the artifact.
---@param hero HeroInstance # Hero that loses the artifact.
---@param artifact Artifact # Artifact to remove, as returned by Services:getArtifactByName.
function AdventureServer:takeArtifact(hero, artifact) end

---Adds creatures to a hero's army.
---@param hero HeroInstance # Hero whose army grows.
---@param creature Creature # Creature to add, as returned by Services:getCreatureByName.
---@param count integer # How many creatures to add. They join an existing stack of the same creature, or take a new army slot; if the army is full of other creatures the new ones are lost.
function AdventureServer:grantCreatures(hero, creature, count) end

---Removes creatures of one type from a hero's army.
---@param hero HeroInstance # Hero whose army shrinks.
---@param creature Creature # Creature to remove, as returned by Services:getCreatureByName.
---@param count integer # How many to remove. If the hero has fewer, all of them are removed. Emptied stacks disappear.
function AdventureServer:takeCreatures(hero, creature, count) end

---Gives a war machine to a hero, placing it in its dedicated equipment slot. Has no effect if the hero already carries a war machine in that slot.
---@param hero HeroInstance # Hero that receives the war machine.
---@param machine Artifact # War machine to give, as returned by Services:getArtifactByName.
function AdventureServer:grantWarMachine(hero, machine) end

---Removes a war machine from a hero. Does nothing if the hero did not carry it.
---@param hero HeroInstance # Hero that loses the war machine.
---@param machine Artifact # War machine to remove, as returned by Services:getArtifactByName.
function AdventureServer:takeWarMachine(hero, machine) end

---Gives a spellbook to a hero, without which learned spells cannot be cast in combat. Does nothing if the hero already has a spellbook.
---@param hero HeroInstance # Hero that receives the spellbook.
function AdventureServer:grantSpellbook(hero) end

---Removes the hero's spellbook. The hero keeps the list of learned spells but can no longer cast them until given a spellbook again. Does nothing if the hero had no spellbook.
---@param hero HeroInstance # Hero that loses the spellbook.
function AdventureServer:takeSpellbook(hero) end

---Gives a hero a temporary morale bonus that lasts until the end of the hero's next battle. Repeated calls each add another separate bonus rather than replacing the previous one.
---@param hero HeroInstance # Hero that receives the morale change.
---@param amount integer # Morale points to add; use a negative number to lower morale.
function AdventureServer:grantMorale(hero, amount) end

---Gives a hero a temporary luck bonus that lasts until the end of the hero's next battle. Repeated calls each add another separate bonus rather than replacing the previous one.
---@param hero HeroInstance # Hero that receives the luck change.
---@param amount integer # Luck points to add; use a negative number to lower luck.
function AdventureServer:grantLuck(hero, amount) end

---Changes a hero's remaining spell points. The mode selects whether the amount is added, subtracted or set as the new total.
---@param hero HeroInstance # Hero whose spell points change.
---@param amount integer # Spell points involved in the change.
---@param mode integer # 0 adds the amount, 1 subtracts it (clamped at zero), 2 sets the total to the amount.
function AdventureServer:grantSpellPoints(hero, amount, mode) end

---Changes a hero's remaining movement points for the current turn. The mode selects whether the amount is added, subtracted or set.
---@param hero HeroInstance # Hero whose movement points change.
---@param amount integer # Movement points involved in the change.
---@param mode integer # 0 adds the amount, 1 subtracts it (clamped at zero), 2 sets the total to the amount.
function AdventureServer:grantMovementPoints(hero, amount, mode) end

---Changes the number of creatures available to hire at one tier of a town on the map.
---@param town TownInstance # Town whose pool of creatures available to hire changes.
---@param level integer # Creature tier (0-7) whose available pool is modified.
---@param count integer # How many extra creatures become available to hire at that tier. Use a negative number to reduce the pool; it is clamped at zero.
function AdventureServer:grantCreaturesToHire(town, level, count) end

---Erects a building in a town for free, ignoring the usual cost and prerequisites.
---@param town TownInstance # Town that gains the building.
---@param building integer # Identifier of the building to erect.
function AdventureServer:constructBuilding(town, building) end

---Pops up a message box for one player. This call does not wait for the player to react - the script continues immediately and the box is shown at the next opportunity. Use it for notifications, not for questions.
---@param player integer # Player who should see the message. Other players see nothing.
---@param text MetaString # The message text, built with MetaString so it can be translated and can embed names and numbers.
---@param components Component[]? # Optional icons shown under the text, such as awarded resources or artifacts. Omit for a plain text box.
---@param soundID integer? # Optional sound to play when the message opens. Omit for the default.
---@param windowType integer? # Optional look of the window. Omit to let the engine pick automatically based on the contents.
function AdventureServer:showMessage(player, text, components, soundID, windowType) end

---Internal plumbing for the blocking showQuestion / showRewardsMessage helpers: shows a modal dialog and registers the query whose reply resumes the paused script. Scripts should call showQuestion / showRewardsMessage instead.
---@param player integer # Player who must answer the dialog.
---@param text MetaString # The dialog text, built with MetaString.
---@param mode integer # 0 shows a plain acknowledge box; any other value shows a yes/no question.
---@param components Component[]? # Optional icons shown under the text.
function AdventureServer:spawnDialog(player, text, mode, components) end

---Internal plumbing for the startCombat helper: replaces the host object's garrison with the given creatures and starts a battle against the visiting hero. Scripts should call startCombat instead.
---@param host MapObject # The visited event/pandora whose garrison is replaced with the opposing army.
---@param hero HeroInstance # Hero that fights the army.
---@param army any # List of {count, creatureKey} pairs describing the opposing army.
function AdventureServer:spawnCombat(host, hero, army) end

---A static artifact definition from the game database. Identifies an artifact kind; concrete instances worn by heroes are a separate concept not currently exposed to scripts.
---@class Artifact
local Artifact = {}

---Returns the JSON key (mod-scoped identifier) of this entity.
---@return string
function Artifact:getJsonKey() end

---True if the artifact occupies the 'big' artifact slot (cannot be carried in the backpack).
---@return boolean
function Artifact:isBig() end

---True if the artifact can be traded between heroes or sold at the marketplace.
---@return boolean
function Artifact:isTradable() end

---Returns the artifact's gold value.
---@return integer
function Artifact:getPrice() end

---Battlefield query interface. The handle scripts receive whenever they are passed a battle context — enumerate units and obstacles, test hex accessibility and shooting penalties, inspect wall state on siege maps. Read-only; mutations go through Server.
---@class Battle
local Battle = {}

---Returns the available tactic phase distance, or 0 if the tactic phase has ended.
---@return integer
function Battle:getTacticDistance() end

---Returns an empty hex next to desired location that the creature can be placed on.
---@param creature Creature # Creature template whose footprint is being placed.
---@param side BattleSide # Side whose deployment area to search.
---@param hex BattleHex? # Preferred origin hex; nil falls back to a side-appropriate default.
---@return BattleHex # Empty hex closest to the desired location that fits the creature, or INVALID if none.
function Battle:getAvailableHex(creature, side, hex) end

---Returns all units for which the predicate returns true.
---@param predicate fun(u: Unit): boolean # Selector — called for each unit on the battlefield; unit is kept when it returns true.
---@return Unit[] # Units for which the predicate returned true.
function Battle:getUnitsIf(predicate) end

---True if the given hex is reachable by the given unit either on current turn or on any future turns.
---@param unit Unit # Unit whose movement model is consulted.
---@param hex BattleHex # Hex to test for reachability.
---@return boolean
function Battle:isAccessibleForUnit(unit, hex) end

---True if a unit of the given creature could be placed on the given hex. Use before summoning a unit; unlike `isAccessibleForUnit` it needs no existing unit to ask about.
---@param hex BattleHex # Hex the unit would be placed on. For a double-wide creature this is its front hex.
---@param creature Creature # Creature that would be placed there.
---@param side BattleSide # Battle side the unit would belong to, which decides where its second hex goes.
---@return boolean
function Battle:isAccessibleForNewUnit(hex, creature, side) end

---Returns the number of hex columns on the battlefield, including the two edge columns that units cannot stand on.
---@return integer
function Battle:getFieldWidth() end

---True if a ranged attack along this line crosses a wall or moat (per the flags).
---@param from BattleHex # Origin hex of the ranged attack.
---@param dest BattleHex # Target hex of the ranged attack.
---@param checkWall boolean # Pass true to count crossing a wall as a penalty source.
---@param checkMoat boolean # Pass true to count crossing a moat as a penalty source.
---@return boolean
function Battle:hasPenaltyOnLine(from, dest, checkWall, checkMoat) end

---True if the attacker stands where it could hit the defender in melee. False for units that an area attack reached without being adjacent to them, such as a dragon breath's second target.
---@param attacker Unit # Unit that would strike.
---@param defender Unit # Unit that would be struck.
---@return boolean
function Battle:isMeleeAttackPossible(attacker, defender) end

---True if the shooter is too far from the target for a full-strength shot. Optionally, perform calculation assuming that units are at specified positions instead of their current ones.
---@param shooter Unit # Unit making the ranged attack.
---@param target Unit # Unit being shot at.
---@param shooterHex BattleHex? # Hex to shoot from; nil uses where the shooter stands.
---@param targetHex BattleHex? # Hex to shoot at; nil uses where the target stands.
---@return boolean
function Battle:hasDistancePenalty(shooter, target, shooterHex, targetHex) end

---True if a town wall stands between the shooter and the target. Optionally, perform calculation assuming that units are at specified positions instead of their current ones.
---@param shooter Unit # Unit making the ranged attack.
---@param target Unit # Unit being shot at.
---@param shooterHex BattleHex? # Hex to shoot from; nil uses where the shooter stands.
---@param targetHex BattleHex? # Hex to shoot at; nil uses where the target stands.
---@return boolean
function Battle:hasWallPenalty(shooter, target, shooterHex, targetHex) end

---True if the attacker would have to turn around to strike the defender. Optionally, perform calculation assuming that units are at specified positions instead of their current ones.
---@param attacker Unit # Unit that would strike.
---@param defender Unit # Unit that would be struck.
---@param attackerHex BattleHex? # Hex to strike from; nil uses where the attacker stands.
---@param defenderHex BattleHex? # Hex to strike at; nil uses where the defender stands.
---@return boolean
function Battle:isToReverse(attacker, defender, attackerHex, defenderHex) end

---Returns the town being defended in this battle.
---@return TownInstance # The besieged town, or nil when the battle is no siege.
function Battle:getDefendedTown() end

---Returns the unit covering the given hex, or nil.
---@param hex BattleHex # Hex to inspect for a unit.
---@param onlyAlive boolean # Pass true to skip dead-but-resurrectable stacks.
---@return Unit
function Battle:getUnitByPos(hex, onlyAlive) end

---Returns all obstacles on the battlefield.
---@return Obstacle[]
function Battle:getAllObstacles() end

---Returns the obstacles on the given hex.
---@param hex BattleHex # Hex whose obstacles are queried.
---@param onlyBlocking boolean # Pass true to limit results to obstacles that block movement.
---@return Obstacle[]
function Battle:getObstaclesOnPos(hex, onlyBlocking) end

---True if the battle is a siege with fortifications present.
---@return boolean
function Battle:hasFortifications() end

---True if the battlefield has a moat.
---@return boolean
function Battle:hasMoat() end

---True if the given side has at least one native-terrain stack.
---@param side BattleSide # Battle side to inspect (attacker or defender).
---@return boolean
function Battle:hasNativeStack(side) end

---Returns every valid battlefield hex.
---@return BattleHexArray
function Battle:getAllPossibleHexes() end

---Returns the current state of the given wall section, or nil if absent.
---@param part WallPart # Wall section to query.
---@return integer?
function Battle:getWallState(part) end

---True if the given wall section can be targeted by an attack.
---@param part WallPart # Wall section to test.
---@return boolean
function Battle:isWallPartAttackable(part) end

---Returns the battle hex corresponding to the given wall section.
---@param part WallPart # Wall section to look up.
---@return BattleHex
function Battle:wallPartToBattleHex(part) end

---Returns the wall section corresponding to the given battle hex.
---@param hex BattleHex # Hex to look up.
---@return WallPart
function Battle:hexToWallPart(hex) end

---Returns the hex used by the tower shooter for the given wall section.
---@param part WallPart # Wall section whose tower-shooter hex is queried.
---@return BattleHex
function Battle:getTowerShooterHex(part) end

---Represents a single tile on the battlefield gridallows computing geometric relationships (distance, neighbours, line-of-sight) that don't rely on current state of a battlefield
---@class BattleHex
local BattleHex = {}

---Returns true if this hex value identifies existing battlefield position.
---@return boolean
function BattleHex:isValid() end

---Returns true if the hex is on the battlefield and is not located in the first or last column, which are reserved for back tile of war machines and are not accessible for regular movement. NOTE: does NOT checks whether hex is blocked by obstacles or units
---@return boolean
function BattleHex:isAvailable() end

---Searches provided array for hex that is closest to current one. If multiple equidistant hexes are found, this function will prefer hex closest to specified battle side.
---@param side BattleSide # Tie-breaker side — closer to this side wins when several candidates are equidistant.
---@param hexes BattleHexArray # Candidate hexes to search through.
---@return BattleHex
function BattleHex:getClosestTile(side, hexes) end

---Returns the neighbouring hex one step north-west.
---@return BattleHex
function BattleHex:copyToNorthWest() end

---Returns the neighbouring hex one step north-east.
---@return BattleHex
function BattleHex:copyToNorthEast() end

---Returns the neighbouring hex one step east.
---@return BattleHex
function BattleHex:copyToEast() end

---Returns the neighbouring hex one step south-east.
---@return BattleHex
function BattleHex:copyToSouthEast() end

---Returns the neighbouring hex one step south-west.
---@return BattleHex
function BattleHex:copyToSouthWest() end

---Returns the neighbouring hex one step west.
---@return BattleHex
function BattleHex:copyToWest() end

---Returns the column of this hex, from 0 at the left edge of the battlefield to 16 at the right one. The two edge columns only hold the heroes, so no unit ever stands there.
---@return integer
function BattleHex:getX() end

---Returns the row of this hex, from 0 at the top of the battlefield to 10 at the bottom. Odd rows are shifted half a hex to the right.
---@return integer
function BattleHex:getY() end

---A list of BattleHex values. Used wherever the engine returns or accepts a set of tiles (reachable hexes, area-of-effect, obstacle footprint, …). Supports indexed access, insertion, and erasure; iteration order matches insertion order
---@class BattleHexArray
local BattleHexArray = {}

---Adds the given hex to the list (no-op if already present).
---@param hex BattleHex # Hex to insert.
function BattleHexArray:insert(hex) end

---Removes the given hex from the list (no-op if absent).
---@param hex BattleHex # Hex to remove.
function BattleHexArray:erase(hex) end

---True if the list contains the given hex.
---@param hex BattleHex # Hex to test for membership.
---@return boolean
function BattleHexArray:contains(hex) end

---Returns the number of unique hexes stored in the list.
---@return integer
function BattleHexArray:size() end

---Returns the hex at the given 1-based index.
---@param index integer # 1-based position of the hex to fetch.
---@return BattleHex
function BattleHexArray:at(index) end

---The authoritative battle mutation interface. Available only to scripts running on the server: spawn or remove battle units, move them, deal damage, alter bonuses, drop obstacles, append to the combat log, draw from the seeded RNG. Every call emits a network pack so clients receive the resulting state change.
---@class BattleServer
local BattleServer = {}

---Spawns a new battle unit described by the given UnitInfo. Returns the created unit.
---@param battle Battle # Battle in which the unit is created.
---@param info UnitInfo # Descriptor of the unit to spawn (creature type, side, position, ...).
---@return Unit
function BattleServer:addUnit(battle, info) end

---Heals the given unit by the provided amount of health points.
---@param battle Battle # Battle in which the unit is healed.
---@param unit Unit # Target unit.
---@param amount integer # Hit points to restore.
---@param level HealLevel # Heal tier (heal / resurrect / overheal).
---@param power HealPower # Persistence — one-battle vs permanent.
---@return integer, integer # Healed hit points, and the count of creatures resurrected.
function BattleServer:healUnit(battle, unit, amount, level, power) end

---Applies a UnitState mutation to the unit, optionally adjusting current health.
---@param battle Battle # Battle in which the unit is modified.
---@param unitState UnitState # New unit state to apply (returned by `Unit:copy`).
---@param healthDelta integer? # Optional health delta — positive heals, negative damages.
function BattleServer:changeUnit(battle, unitState, healthDelta) end

---Damages the unit, returning the actual damage dealt and the number of killed creatures.
---@param battle Battle # Battle in which damage is dealt.
---@param unit Unit # Target unit.
---@param damage integer # Damage points to deal (will be clamped to remaining health).
---@return integer, integer # Damage actually dealt, and the count of killed creatures.
function BattleServer:damageUnit(battle, unit, damage) end

---Removes the unit or its corpse from the battlefield.
---@param battle Battle # Battle the unit belongs to.
---@param unit Unit # Unit (alive or as corpse) to remove.
function BattleServer:removeUnit(battle, unit) end

---Removes the given obstacle from the battlefield.
---@param battle Battle # Battle the obstacle belongs to.
---@param obstacle Obstacle # Obstacle to remove.
function BattleServer:removeObstacle(battle, obstacle) end

---Moves the unit to the destination hex.
---@param battle Battle # Battle in which the unit is moved.
---@param unit Unit # Unit to move.
---@param destination BattleHex # Target hex of the move.
---@param isTeleport boolean # Pass true to use teleport semantics (no path walk).
function BattleServer:moveUnit(battle, unit, destination, isTeleport) end

---Appends a formatted log entry to the battle log.
---@param battle Battle # Battle whose log is being appended.
---@param message MetaString # Formatted log line (use `MetaString`).
function BattleServer:appendLog(battle, message) end

---Returns whether netpack changes should be described in the battle log.
---@return boolean
function BattleServer:describeChanges() end

---Removes the listed bonuses from the unit.
---@param battle Battle # Battle the unit belongs to.
---@param unit Unit # Unit whose bonuses are removed.
---@param bonusList BonusList # Bonuses to remove from the unit.
function BattleServer:removeUnitBonuses(battle, unit, bonusList) end

---Adds a bonus described by the descriptor to the unit.
---@param battle Battle # Battle the unit belongs to.
---@param unit Unit # Unit to add the bonus to.
---@param descriptor BonusDescriptor # BonusDescriptor that creates the bonus.
---@param cumulative boolean # Pass true to stack with existing same-source bonus, false to update in-place.
function BattleServer:addUnitBonus(battle, unit, descriptor, cumulative) end

---Adds a bonus to the battle-wide bonus set.
---@param battle Battle # Battle to attach the bonus to.
---@param descriptor BonusDescriptor # BonusDescriptor that creates the bonus.
function BattleServer:addBattleBonus(battle, descriptor) end

---Creates a new obstacle described by the descriptor on the battlefield.
---@param battle Battle # Battle the obstacle is placed in.
---@param descriptor SpellObstacleDescriptor # SpellObstacleDescriptor describing the obstacle to create.
function BattleServer:addObstacle(battle, descriptor) end

---Performs a catapult attack against the given wall section, dealing the supplied damage.
---@param battle Battle # Battle in which the catapult attack happens.
---@param attacker Unit # Unit performing the catapult attack, or nil for spell-caused attacks.
---@param attackedPart WallPart # Wall section to attack.
---@param damageDealt integer # Damage to apply to the wall section.
function BattleServer:catapultAttack(battle, attacker, attackedPart, damageDealt) end

---Returns a server-side random integer in the inclusive range [low, high].
---@param low integer # Inclusive lower bound.
---@param high integer # Inclusive upper bound.
---@return integer # Random integer in [low, high].
function BattleServer:rngInt(low, high) end

---Rolls the same chance many times over and returns how many succeeded. Use this rather than a loop over `rngInt` for abilities that roll once per creature in a stack, which can number in the thousands.
---@param trials integer # How many independent chances are rolled.
---@param chance number # Chance of each one succeeding, from 0 to 1.
---@return integer # How many of them succeeded.
function BattleServer:rngBinomial(trials, chance) end

---Rolls a chance-based combat ability. Use this rather than `rngInt` for abilities that trigger with a percentage chance - it draws from the per-army biased sequence
---@param battle Battle # Battle the acting unit fights in.
---@param actor Unit # Unit whose ability is being rolled.
---@param percentageChance integer # Chance to succeed, in percent.
---@return boolean # True if the ability triggers.
function BattleServer:rollCombatAbility(battle, actor, percentageChance) end

---Casts a spell as a passive ability of the caster: announces it so that clients play its animation and sound, filters the targets through the spell's own immunity rules, and applies its effects with the given magnitude. Casting this way never fires a combat event, so a script that casts cannot re-enter itself.
---@param battle Battle # Battle the spell is cast in.
---@param caster Unit # Unit whose ability casts the spell.
---@param spell Spell # Spell to cast.
---@param target Unit[] # Units the spell is aimed at.
---@param effectValue integer # Magnitude handed to the spell's effects, for spells that take one.
function BattleServer:castSpell(battle, caster, spell, target, effectValue) end

---Applies the effects of a spell to the given units, and nothing else. Unlike casting the spell, the target list is used as given rather than expanded through the spell's range, magic resistance and magic mirror are not rolled, countering effects are not removed, and no spell animation or battle log entry is produced. Use it for abilities that behave as if the spell were already in effect.
---@param battle Battle # Battle the spell is applied in.
---@param caster Unit # Unit acting as the caster. Its stats scale the effects.
---@param spell Spell # Spell whose effects are applied.
---@param target Unit[] # Units to affect.
---@param spellLevel integer # Mastery level the effects are applied at.
---@param effectDuration integer # How many turns timed effects of the spell last.
---@param ignoreImmunity boolean # Pass true to affect units that are immune to the spell.
function BattleServer:applySpellEffects(battle, caster, spell, target, spellLevel, effectDuration, ignoreImmunity) end

---Plays a one-shot animation on the battlefield. Changes no game state, so use it to give a visual to a change the script made itself. The animation plays after whatever is currently animating has finished, rather than overlapping it. A deferred animation instead plays together with the animations of the next change the script makes, e.g. the flinch of a unit it damages right after - and is dropped if no such change follows.
---@param battle Battle # Battle the animation is played in.
---@param target Destination[] # Units and hexes the animation is played on, one copy each.
---@param animation string # Resource name of the animation to play, e.g. `SP06_`.
---@param sound string # Resource name of the sound to play alongside it, or an empty string for none.
---@param transparency number # Opacity of the animation, from 0 for invisible to 1 for opaque.
---@param deferred boolean? # Pass true to hold the animation back until the next change the script makes, so that both play at once.
function BattleServer:showBattleAnimation(battle, target, animation, sound, transparency, deferred) end

---Makes the client play back pending unit changes. Needed after adding or removing units outside of an attack, which otherwise produce no animation.
---@param battle Battle # Battle whose units were changed.
function BattleServer:refreshBattleUnits(battle) end

---A single effect contributing to target abilities (e.g. +5 attack, immunity to fire spells). Carries type, value, source, duration, stacking key. Scripts read bonuses through `getBonuses(...)` and construct new ones via addUnitBonus or addBattleBonus in ServerCallback.
---@class Bonus
local Bonus = {}

---Returns the bonus type as its JSON key.
---@return string
function Bonus:getType() end

---Returns the integer magnitude of the bonus.
---@return integer
function Bonus:getVal() end

---Returns the bonus subtype as a JSON key (the meaning depends on getType).
---@return string
function Bonus:getSubtype() end

---Returns the JSON key identifying the entity that granted this bonus.
---@return string
function Bonus:getSourceID() end

---Returns the source category (artifact, creature ability, spell, ...) of the bonus.
---@return BonusSource
function Bonus:getSource() end

---Returns the kind of combat the bonus is limited to. A bonus that applies to melee only is silently absent while shooting, and the other way round.
---@return BonusLimitEffect
function Bonus:getEffectRange() end

---Returns the list of duration flags currently set on the bonus.
---@return BonusDuration[]
function Bonus:getDuration() end

---Returns how the value combines with other bonuses (additive, percent, base number, ...).
---@return BonusValueType
function Bonus:getValType() end

---Returns the stacking key — bonuses with the same key from the same source do not stack.
---@return string
function Bonus:getStacking() end

---Returns the remaining turns until the bonus expires (0 if not turn-limited, only active if duration is set accordingly).
---@return integer
function Bonus:getTurnsRemain() end

---True if the bonus is hidden from the player's interface display.
---@return boolean
function Bonus:isHidden() end

---Returns the bonus's extra parameters encoded as a single integer (0 if none).
---@return integer
function Bonus:getParametersAsNumber() end

---Returns the bonus's extra parameters as a list of integers (empty if not stored as an array).
---@return integer[]
function Bonus:getParametersAsVector() end

---Configuration for a Bonus that scripts hand to ServerCallback `addUnitBonus` or `addBattleBonus`. Fields mirror the JSON bonus definition. See bonus docs for more details.
---@class BonusDescriptor
---@field val integer # Numeric magnitude of the bonus (interpreted per `valueType`).
---@field turns integer # Remaining duration in turns; relevant for the N_TURNS / N_DAYS durations.
---@field hidden boolean # If true, the bonus is not shown in the unit's bonus list UI.
---@field stacking string # Stacking key — bonuses sharing it overwrite rather than accumulate.
---@field description string # Optional human-readable description (used by tooltips when shown). Overrides generic description for this bonus type.
---@field icon string # Optional icon name shown next to the bonus in the UI. Overrides generic icon for this bonus type.
---@field type any # Bonus type name (e.g. PRIMARY_SKILL, FIRE_IMMUNITY). See Bonus types documentation.
---@field subtype any # Sub-selector that narrows the type (e.g. specific creature, school, primary stat).
---@field valueType any # How `val` is combined with other bonuses: additive, base, percent-of-..., independent min/max.
---@field effectRange any # Spatial scope the bonus applies in (e.g. ranged-only or melee-only).
---@field duration any # When the bonus expires — permanent, one-battle, n-turns, until-attacked, etc.
---@field sourceType any # Origin class (artifact, spell effect, secondary skill, …) — drives source-based dispels.
---@field sourceID any # Identifier of the specific source within its sourceType.
---@field targetSourceType any # Source type the bonus is restricted to act upon (used by hero specialty bonuses).
---@field addInfo any # Optional auxiliary payload — meaning depends on the bonus type.
---@field limiters any # JSON-defined limiter chain that definea whether the bonus applies to a given bearer.
---@field propagator any # Rule for propagating the bonus upwards for area effect (army-wide, player-wide, …).
---@field updater any # Rules for recalculation of bonus parameters (e.g. scales with stack count).
---@field propagationUpdater any # Updater applied to bonuses produced by this one's propagator.
local BonusDescriptor = {}

---Which bonuses of a bearer a query is about, handed to `getBonuses`, `getBonusesValue` and `hasBonuses` as a plain table. Every field left out widens the answer, so `{}` asks for all of them.
---@class BonusFilter
---@field type string? # Bonus type to look for, by its json key.
---@field subtype string? # Subtype to look for, by its json key. Requires a type.
---@field sourceType BonusSource? # Where the bonus has to come from - an artifact, a spell effect, ...
---@field shooting boolean? # Kind of blow the bonus has to count for - pass the `shooting` flag of the attack. Bonuses limited to the other kind are left out, those limited to neither always count.
local BonusFilter = {}

---A collection of Bonus values returned by `getBonuses(...)`. Use `size()` and `getBonus(index)` to iterate. A copy of the engine's internal list at the moment of the call — changes to holder afterwards will not affect this snapshot.
---@class BonusList
local BonusList = {}

---Returns the number of bonuses in this list.
---@return integer
function BonusList:size() end

---Computes total value of bonuses in the list, accounting for bonus value types
---@return integer
function BonusList:totalValue() end

---Returns the bonuses of this list the predicate accepts. Use to narrow a list down before `totalValue`, which combines what is left by the rules of the engine.
---@param predicate fun(b: Bonus): boolean # Selector — called for each bonus of the list; bonus is kept when it returns true.
---@return BonusList # Bonuses for which the predicate returned true.
function BonusList:filter(predicate) end

---Returns the bonus at the given 1-based index. Aborts the script if the index is out of range.
---@param index integer # 1-based position of the bonus to fetch.
---@return Bonus # Bonus stored at the given position.
function BonusList:getBonus(index) end

---A building of a town, as `TownInstance:getBuildings` reports it.
---@class Building
local Building = {}

---Returns the json key of this building, such as `core:fort`.
---@return string # Identifier of this building, scoped by the mod providing it.
function Building:getJsonKey() end

---Returns which of the buildings known to the game this one is. Unlike the json key this is the same in every town, so it is what to test against when a rule speaks of a fort or a town hall rather than of one particular mod's version of it.
---@return string? # "fort", "villageHall", ...; nil for a building the game has no name of its own for.
function Building:getBuildingType() end

---Whether this building is an upgrade of another, as a citadel is of a fort.
---@return boolean # True when this building improves another one instead of standing on its own.
function Building:isUpgrade() end

---Interprets an in-game day count using the map's calendar settings (days per week, weeks per month). Obtained from Game:getCalendar().
---@class Calendar
local Calendar = {}

---Returns the current day count.
---@return integer # Total number of days since the start of the game (1..).
function Calendar:getCurrentDay() end

---Returns the day within the current week.
---@return integer # Day within the current week (1..days-per-week).
function Calendar:getDayOfWeek() end

---Returns the day within the current month.
---@return integer # Day within the current month (1..days-per-month).
function Calendar:getDayOfMonth() end

---Returns the week within the current month.
---@return integer # Week within the current month (1..weeks-per-month).
function Calendar:getWeek() end

---Returns the current month.
---@return integer # Current month (1..).
function Calendar:getMonth() end

---Returns the number of days in a week.
---@return integer # Configured number of days per week.
function Calendar:getDaysInWeek() end

---Returns the number of days in a month.
---@return integer # Configured number of days per month.
function Calendar:getDaysInMonth() end

---Returns the number of weeks in a month.
---@return integer # Configured number of weeks per month.
function Calendar:getWeeksInMonth() end

---Descriptor for an icon shown in a message window (a creature, artifact, resource, skill, ... with an optional amount). `type` selects the kind and `subType` the specific entity.
---@class Component
---@field type integer # Component kind (ComponentType index).
---@field subType integer # Identifier index of the entity, interpreted according to `type`.
---@field value integer? # Optional amount: positive means gained, negative means lost.
local Component = {}

---A creature type from the database (e.g. "pikeman"). Carries base stats, faction, recruitment cost, and the bonuses every instance starts with. Concrete battlefield or army-slot instances are Unit and StackInstance respectively.
---@class Creature
local Creature = {}

---Returns the JSON key (mod-scoped identifier) of this entity.
---@return string
function Creature:getJsonKey() end

---Returns the base maximum hit points of a single creature of this type. Equivalent to getBaseHitPoints.
---@return integer
function Creature:getMaxHealth() end

---Select either the singular or plural text ID for the requested amount.
---@param amount integer # Stack size; passes through to the singular form when equal to 1, plural otherwise.
---@return string
function Creature:getNameTextID(amount) end

---Returns the minimum stack size for this creature when generated on the adventure map.
---@return integer
function Creature:getMapAmountMin() end

---Returns the maximum stack size for this creature when generated on the adventure map.
---@return integer
function Creature:getMapAmountMax() end

---Returns the AI value used for army strength calculations.
---@return integer
function Creature:getAIValue() end

---Returns the combat power value of one creature of this type.
---@return integer
function Creature:getFightValue() end

---Returns the creature level, usually in (1..7) range.
---@return integer
function Creature:getLevel() end

---Returns the base weekly growth rate for this creature in town dwellings.
---@return integer
function Creature:getGrowth() end

---Returns the extra growth granted by the horde building (0 if none).
---@return integer
function Creature:getHorde() end

---Returns the recruitment cost in the specified resource.
---@param resourceID integer # JSON key of the resource whose cost is being queried (e.g. `gold`, `ore`).
---@return integer
function Creature:getRecruitCost(resourceID) end

---True if the creature occupies two hexes on the battlefield.
---@return boolean
function Creature:isDoubleWide() end

---The global `ENUM` table — string->integer constants scripts use to avoid magic numbers. Each field below is a named group; the runtime value is a Lua table whose keys are the constant names.
---@class Enums
---@field HealLevel HealLevel # Outcome categories for the heal action: plain heal / resurrect / overheal.
---@field HealPower HealPower # Persistence of healing effects: one-battle vs permanent.
---@field SpellCastProblem SpellCastProblem # Error codes returned from spell-cast validation.
---@field AimType AimType # Targeting modes a spell can require: none, creature, obstacle, location.
---@field BonusDuration BonusDuration # Lifetime selectors used by Bonus / BonusDescriptor `duration`.
---@field BonusSource BonusSource # Origin classes used by Bonus / BonusDescriptor `sourceType`.
---@field BonusValueType BonusValueType # Combination rules used by Bonus / BonusDescriptor `valueType`.
---@field BonusLimitEffect BonusLimitEffect # Kinds of combat a bonus is limited to, used by Bonus `effectRange`.
---@field ObstacleType ObstacleType # Obstacle categories used by SpellObstacleDescriptor `obstacleType`.
---@field WallPart WallPart # Town-wall sections referenced by siege APIs and `catapultAttack`.
---@field BattleSide BattleSide # Battlefield side identifiers: none / attacker / defender.
---@field Difficulty Difficulty # Game difficulty levels, named after chess pieces (pawn = easiest, king = hardest).
---@field PrimarySkill PrimarySkill # The four primary hero skills.
---@field PlayerColor PlayerColor # Player colours, plus the neutral owner used by unowned objects.
---@field PlayerStatus PlayerStatus # Whether a player is still playing, has won, or has lost.
local Enums = {}

---Outcome categories for the heal action: plain heal / resurrect / overheal.
---@enum HealLevel
local HealLevel = {
    ---Standard healing — capped at the stack's current size, does not revive dead.
    heal = 0,
    ---Brings dead creatures in the stack back, up to the starting count.
    resurrect = 1,
    ---Allows increasing size of stack past the starting count.
    overheal = 2,
}

---Persistence of healing effects: one-battle vs permanent.
---@enum HealPower
local HealPower = {
    ---Resurrected troops disapper when the battle ends.
    oneBattle = 0,
    ---Resurrected troops persist into the post-battle stack state.
    permanent = 1,
}

---Error codes returned from spell-cast validation.
---@enum SpellCastProblem
local SpellCastProblem = {
    ---There is no hero available to cast the spell.
    noHeroToCastSpell = 1,
    ---The caster has already used their per-turn cast allowance.
    castsPerTurnLimit = 2,
    ---The caster does not carry a spellbook.
    noSpellbook = 3,
    ---The spell is not present in the caster's spellbook.
    heroDoesntKnowSpell = 4,
    ---The caster does not have enough mana for this spell.
    notEnoughMana = 5,
    ---An adventure-map spell was attempted in battle context.
    advmapSpellInsteadOfBattleSpell = 6,
    ---The caster's wisdom is too low for the spell's level.
    spellLevelLimitExceeded = 7,
    ---Dispel was cast but there are no eligible spells to remove.
    noSpellsToDispel = 8,
    ---No legal target was selected for the spell.
    noAppropriateTarget = 9,
    ---The chosen target unit is immune to this spell.
    stackImmuneToSpell = 10,
    ---The selected target is not valid for this spell's AimType.
    wrongSpellTarget = 11,
    ---Spells may not be cast during the tactic phase.
    ongoinTacticPhase = 12,
    ---Magic is suppressed on this battlefield (anti-magic terrain or effect).
    magicIsBlocked = 13,
}

---Targeting modes a spell can require: none, creature, obstacle, location.
---@enum AimType
local AimType = {
    ---Spell takes no target - massive spells that cast directly when selected.
    nothing = 0,
    ---Spell targets one or more units on the battlefield.
    creature = 1,
    ---Spell targets an existing obstacle.
    obstacle = 2,
    ---Spell targets one or more battlefield hexes (no unit required).
    location = 3,
}

---Lifetime selectors used by Bonus / BonusDescriptor `duration`.
---@enum BonusDuration
local BonusDuration = {
    ---Lasts forever (until explicitly removed).
    permanent = 1,
    ---Expires at the end of the current battle.
    oneBattle = 2,
    ---Expires after end of current in-game day.
    oneDay = 4,
    ---Expires after end of current in-game week.
    oneWeek = 8,
    ---Expires after N battle turns.
    nTurns = 16,
    ---Expires after N in-game days.
    nDays = 32,
    ---Expires the first time the bearer is attacked.
    untilBeingAttacked = 64,
    ---Expires the first time the bearer makes any attack.
    untilAttack = 128,
    ---Expires when the bearer's unit gets to act.
    stackGetsTurn = 256,
    ---Tied to a commander — expires when the commander dies.
    commanderKilled = 512,
    ---Expires when the bearer initiates an attack (not counter-attack).
    untilOwnAttack = 1024,
    ---Expires when the bearer takes spell or environmental damage.
    untilTakingIndirectDamage = 2048,
    ---Expires after the current attack-and-counter sequence resolves.
    untilAfterAttackSequence = 4096,
}

---Origin classes used by Bonus / BonusDescriptor `sourceType`.
---@enum BonusSource
local BonusSource = {
    ---Granted by an artifact definition. Does not stacks if hero has multiple of same artifacts
    artifact = 0,
    ---Granted by a specific equipped artifact instance. Stacks with multiple copies of same artifact
    artifactInstance = 1,
    ---Granted by a map-object type (e.g. Stables).
    objectType = 2,
    ---Granted by a specific instance of map object, stacks with each same object.
    objectInstance = 3,
    ---Innate to the creature type (e.g. dragon breath, undead).
    creatureAbility = 4,
    ---Native-terrain bonus (creature on its faction's home terrain).
    terrainNative = 5,
    ---Battlefield-terrain overlay bonus (magic plains, fiery fields, …).
    terrainOverlay = 6,
    ---Active spell effect on the bearer.
    spellEffect = 7,
    ---Built town structure providing the bonus.
    townStructure = 8,
    ---Hero primary skill (attack/defense/power/knowledge).
    heroBaseSkill = 9,
    ---Hero secondary skill level (Tactics, Offense, Wisdom, …).
    secondarySkill = 10,
    ---Hero specialty (creature affinity, spell affinity, etc.).
    heroSpecial = 11,
    ---Army composition bonus. Currently only used for morale.
    army = 12,
    ---Carry-over bonus from a campaign scenario.
    campaignBonus = 13,
    ---Stack-experience rank bonus.
    stackExperience = 14,
    ---Commander unit ability.
    commander = 15,
    ---Map-wide global effect. Defined in game settings.
    global = 16,
    ---Source not represented by another category.
    other = 17,
}

---Combination rules used by Bonus / BonusDescriptor `valueType`.
---@enum BonusValueType
local BonusValueType = {
    ---Adds to the base value, but after `percent to base`.
    additiveValue = 0,
    ---Adds the base value before any additive/percent steps.
    baseNumber = 1,
    ---Percentage applied to the running total of all sources combined.
    percentToAll = 2,
    ---Percentage applied to the base value only.
    percentToBase = 3,
    ---Percentage applied to the same-source subtotal.
    percentToSource = 4,
    ---Percentage applied only to bonuses from a matching targetSourceType.
    percentToTargetType = 5,
    ---Independent ceiling — wins if greater than the accumulated value.
    independentMax = 6,
    ---Independent floor — wins if smaller than the accumulated value.
    independentMin = 7,
}

---Kinds of combat a bonus is limited to, used by Bonus `effectRange`.
---@enum BonusLimitEffect
local BonusLimitEffect = {
    ---Applies to every kind of combat.
    noLimit = 0,
    ---Applies only while shooting.
    onlyDistanceFight = 1,
    ---Applies only in melee.
    onlyMeleeFight = 2,
}

---Obstacle categories used by SpellObstacleDescriptor `obstacleType`.
---@enum ObstacleType
local ObstacleType = {
    ---Small, randomly placed battlefield obstacles placed on start of the battle.
    usual = 0,
    ---Large obstacle blocking predefined part of the battlefield. At most one such obstacle is present on map.
    absolute = 1,
    ---Obstacle placed by a spell (Land Mine, Quicksand, Fire Wall, …).
    spellCreated = 2,
    ---Town-siege moat tiles.
    moat = 3,
}

---Town-wall sections referenced by siege APIs and `catapultAttack`.
---@enum WallPart
local WallPart = {
    ---No wall part. Returned for hexes outside the fortifications.
    invalid = -1,
    ---Sections of walls that always exist and always block ranged attacks
    indestructiblePart = -2,
    ---Section of gate that always exists, but does not blocks ranged attacks
    indestructibleGate = -3,
    ---Central keep building, usually built by Citadel.
    keep = 0,
    ---Bottom tower of the town walls, usually built by Castle.
    bottomTower = 1,
    ---Destructible wall segment adjacent to bottom tower.
    bottomWall = 2,
    ---Destructible wall segment immediately below the gatehouse.
    belowGate = 3,
    ---Destructible wall segment immediately above the gatehouse.
    overGate = 4,
    ---Destructible wall segment adjacent to the upper tower.
    upperWall = 5,
    ---Upper tower of the town walls, usually built by Castle.
    upperTower = 6,
    ---Destructible town gate that can only be opened by defenders.
    gate = 7,
}

---Battlefield side identifiers: none / attacker / defender.
---@enum BattleSide
local BattleSide = {
    ---Not associated with any side.
    none = -1,
    ---The attacking army that initiated the battle. Equivalent to `left`
    attacker = 0,
    ---The defending army. Equivalent to `right`
    defender = 1,
    ---Army that starts on the left side of the battlefield. Equivalent to `attacker`.
    left = 0,
    ---Army that starts on the right side of the battlefield. Equivalent to `defender`.
    right = 1,
}

---Game difficulty levels, named after chess pieces (pawn = easiest, king = hardest).
---@enum Difficulty
local Difficulty = {
    ---Easy difficulty. (80%)
    pawn = 0,
    ---Normal difficulty. (100%)
    knight = 1,
    ---Hard difficulty. (130%)
    rook = 2,
    ---Expert difficulty. (160%)
    queen = 3,
    ---Impossible difficulty. (200%)
    king = 4,
}

---The four primary hero skills.
---@enum PrimarySkill
local PrimarySkill = {
    ---Attack skill, raises damage dealt by the hero's troops.
    attack = 0,
    ---Defence skill, lowers damage taken by the hero's troops.
    defence = 1,
    ---Spell power, scales the effect of the hero's spells.
    spellpower = 2,
    ---Knowledge, scales the hero's maximum spell points.
    knowledge = 3,
}

---Player colours, plus the neutral owner used by unowned objects.
---@enum PlayerColor
local PlayerColor = {
    ---Player red.
    red = 0,
    ---Player blue.
    blue = 1,
    ---Player tan.
    tan = 2,
    ---Player green.
    green = 3,
    ---Player orange.
    orange = 4,
    ---Player purple.
    purple = 5,
    ---Player teal.
    teal = 6,
    ---Player pink.
    pink = 7,
    ---No owner - used by unowned towns, mines and dwellings.
    neutral = -1,
}

---Whether a player is still playing, has won, or has lost.
---@enum PlayerStatus
local PlayerStatus = {
    ---Player is still playing.
    ingame = 0,
    ---Player has been defeated and is out of the game.
    loser = 1,
    ---Player has won the game.
    winner = 2,
}

---A town/army faction definition (Castle, Rampart, Inferno, …). Identifies the kind, not a placed town; use Game lookups for the latter.
---@class Faction
local Faction = {}

---Returns the JSON key (mod-scoped identifier) of this entity.
---@return string
function Faction:getJsonKey() end

---True if this faction has town belonging to it in the game. Usually true for all factions other than neutral
---@return boolean
function Faction:hasTown() end

---Adventure-map query interface. Provides world-level lookups: current date, players, towns, heroes, and map objects accessible to the calling script's owner.
---@class Game
local Game = {}

---Returns the hero by its object identifier, or nil if not found.
---@param objectID integer # Map object identifier of the hero to fetch.
---@return HeroInstance
function Game:getHero(objectID) end

---Returns the map object by its identifier, or nil if not found.
---@param objectID integer # Map object identifier of the object to fetch.
---@param verbose boolean # Pass true to log a warning when the object isn't found.
---@return MapObject
function Game:getObj(objectID, verbose) end

---Returns the amount of the given resource owned by the player.
---@param player integer # Player whose treasury is queried.
---@param resource ResourceType # Resource to read, as returned by Services:getResourceByName.
---@return integer # Amount of that resource the player currently owns.
function Game:getResource(player, resource) end

---Returns the calendar object for the current in-game date.
---@return Calendar # Calendar for the current in-game date.
function Game:getCalendar() end

---Returns the current game difficulty level.
---@return Difficulty # Current game difficulty; compare against ENUM.Difficulty (pawn..king).
function Game:getDifficulty() end

---Reads back a named value saved earlier with AdventureServer:setMapVariable. Values survive saving and loading, so this is how a script remembers state between visits.
---@param name string # Name of the variable to read, as stored with AdventureServer:setMapVariable.
---@return any # The stored value, or nil when nothing was ever stored under that name.
function Game:getMapVariable(name) end

---Checks whether a named map variable has ever been set, which lets a script tell "unset" apart from a stored value of 0 or false.
---@param name string # Name of the variable to check.
---@return boolean # True when a value has been stored under that name.
function Game:hasMapVariable(name) end

---Tells whether the given player is controlled by a human.
---@param player integer # Player color index to check.
---@return boolean # True when that player is controlled by a human, false for an AI or an unused color.
function Game:playerIsHuman(player) end

---Returns whether the player is still playing, has won, or has been defeated.
---@param player integer # Player whose status is queried.
---@return PlayerStatus # Current status; compare against ENUM.PlayerStatus.
function Game:getPlayerStatus(player) end

---Returns the town faction a player started the map with.
---@param player integer # Player whose starting faction is queried.
---@return Faction # The town faction the player began the map with, or nil when the player has none.
function Game:getPlayerFaction(player) end

---Tells whether a player has already seen the object's current quest proposed, so a script can show the progression text instead of the proposal text on a repeat visit.
---@param target MapObject # The quest source (seer hut / quest guard) to check.
---@param player integer # Player to check.
---@return boolean # True once the player has already been offered the object's active quest.
function Game:wasQuestProposed(target, player) end

---Finds the hero of the given type placed on the map.
---@param heroType HeroType # Hero type to look for, as returned by Services:getHeroTypeByName.
---@return HeroInstance # The hero of that type currently on the map, or nil when no such hero exists.
function Game:getHeroByType(heroType) end

---Tells whether the given player destroyed the given map object.
---@param player integer # Player to check.
---@param target MapObject # Map object to check, e.g. a wandering monster or a hero.
---@return boolean # True when that player destroyed the object.
function Game:playerDestroyedObject(player, target) end

---Looks up a map object by its instance name.
---@param objectName string # Instance name of the object, as resolved through the questObjects table.
---@return MapObject # The map object with that instance name, or nil when the name is empty or unknown.
function Game:getObjectByName(objectName) end

---Hero class definition (Knight, Cleric, Ranger, …). Static metadata shared by all heroes of that class; for a placed hero use HeroInstance.
---@class HeroClass
local HeroClass = {}

---Returns the JSON key (mod-scoped identifier) of this entity.
---@return string
function HeroClass:getJsonKey() end

---A hero placed on the adventure map. Provides access to such information as owner, type (Orrin, Kyrre, Astral...), position on map, artifacts, and secondary skills, army composition, primary skills, and all bonuses affecting hero.
---@class HeroInstance
local HeroInstance = {}

---Returns the bonuses of the bearer that match the filter. Say as much as the filter can express, since that is also what the engine can cache; narrow whatever is left with `BonusList:filter`.
---@param filter BonusFilter # Which bonuses to collect. An empty filter collects every one of them.
---@return BonusList # Bonuses of the bearer the filter describes.
function HeroInstance:getBonuses(filter) end

---Returns what the matching bonuses are worth together. Not a plain sum - percentages, independent floors and ceilings combine by the rules of the engine. Prefer this over adding up `getBonuses` where possible.
---@param filter BonusFilter # Which bonuses to count. An empty filter counts every one of them.
---@return integer # Value of the matching bonuses taken together.
function HeroInstance:getBonusesValue(filter) end

---True if the bearer carries a bonus the filter describes. Prefer this over testing the size of `getBonuses`, which hands the whole list over to the script to answer a question the engine can answer on its own.
---@param filter BonusFilter # Which bonuses to look for. An empty filter asks whether the bearer has any at all.
---@return boolean # True if the bearer carries at least one matching bonus.
function HeroInstance:hasBonuses(filter) end

---Returns the stack instance in the given army slot, or nil if the slot is empty.
---@param slot integer # Army slot to query (1-based).
---@return StackInstance
function HeroInstance:getStack(slot) end

---Returns the player color that owns this hero.
---@return integer
function HeroInstance:getOwner() end

---Returns the text ID of the hero's name.
---@return string
function HeroInstance:getNameTextID() end

---True if the hero's gender is male.
---@return boolean
function HeroInstance:isMale() end

---True if the hero's gender is female.
---@return boolean
function HeroInstance:isFemale() end

---Returns the hero's current level.
---@return integer # Current level of the hero.
function HeroInstance:getLevel() end

---Returns the hero's total experience points.
---@return integer # Total experience points of the hero.
function HeroInstance:getExperience() end

---Returns the value of one of the hero's primary skills.
---@param skill integer # Primary skill JSON key (`attack`, `defence`, `spellpower`, `knowledge`).
---@return integer # Current value of the primary skill.
function HeroInstance:getPrimarySkill(skill) end

---Returns the hero's mastery of the given secondary skill.
---@param skill integer # Secondary skill JSON key.
---@return integer # Mastery level (0 = none, 1 = basic, 2 = advanced, 3 = expert).
function HeroInstance:getSecondarySkill(skill) end

---Returns whether the hero owns the given artifact, either as equipped or in the backpack.
---@param artifact integer # Artifact JSON key.
---@return boolean # True if the hero owns the artifact.
function HeroInstance:hasArtifact(artifact) end

---Returns how many copies of the given artifact the hero owns, counting both equipped slots and the backpack.
---@param artifact integer # Artifact JSON key.
---@return integer # Number of copies of that artifact the hero carries.
function HeroInstance:ownedArtifacts(artifact) end

---Returns how many creatures of the given type are in the hero's army across all unit stacks.
---@param creature integer # Creature JSON key.
---@return integer # Total number of that creature across the hero's army.
function HeroInstance:creatureCountInArmy(creature) end

---A specific named hero from the database (Sir Mullich, Crag Hack, …). Identifies the hero kind and their starting profile; the in-game placed hero is HeroInstance.
---@class HeroType
local HeroType = {}

---Returns the JSON key (mod-scoped identifier) of this entity.
---@return string
function HeroType:getJsonKey() end

---A handle to an adventure-map object (event, town, monster, resource, ...). Right now used only to identify the object a trigger fired on, so scripts can act on it (e.g. remove it).
---@class MapObject
local MapObject = {}

---Returns the owner of this map object.
---@return integer # Player that owns this object, or the neutral player when unowned.
function MapObject:getOwner() end

---Returns the map-unique instance name identifying this object.
---@return string # The object's unique instance name, as set in the map editor or auto-generated.
function MapObject:getInstanceName() end

---Setup handle given to a map script's init method. Lets the script list the map's objects and bind its handler functions to event objects by their instance name.
---@class MapSetup
local MapSetup = {}

---Binds one of the script's handler functions to a map event object: visiting that object then runs the named function (with the usual game, server, object, hero arguments) instead of the object's default reward. Errors if no object has that instance name or the object is not an event/pandora.
---@param funcName string # Name of the script function to run when the object is visited.
---@param objectName string # Instance name of the event/pandora object to bind the handler to.
function MapSetup:attachEventScript(funcName, objectName) end

---Returns all objects on the map so the script can find the ones to attach handlers to (match on getInstanceName).
---@return MapObject[] # Every object currently placed on the map.
function MapSetup:objects() end

---Object for constructing strings with translation support. Supports appending text via `append` field and `replaceStrings` / `replaceNumbers` to fill the %s and %d placeholders. Used in all places that expect translatable string with formattingsuch as battle log and spell-problem messages. In case of multiplayer, string is translated on each client according to their language settings
---@class MetaString
---@field append string[] # Sequence of text-ID tokens to concatenate.
---@field replaceStrings string[] # Values that fill %s placeholders in the appended tokens, in order.
---@field replaceNumbers integer[] # Values that fill %d placeholders in the appended tokens, in order.
local MetaString = {}

---A battlefield obstacle (static map decoration, moat tile, or spell-created hazard). Exposed read-only — to add or remove obstacles use the `server:addObstacle` or `server:removeObstacle` methods.
---@class Obstacle
local Obstacle = {}

---Returns the obstacle category: usual, absolute, moat, or spell-created.
---@return ObstacleType
function Obstacle:getObstacleType() end

---Returns the hex that serves as anchor of the obstacle, usually - located in bottom-left corner of the obstacle
---@return BattleHex
function Obstacle:getPosition() end

---Returns the Spell that created this obstacle, or nil for non-spell obstacles.
---@return Spell
function Obstacle:getSpell() end

---A resource definition (wood, ore, gold, ...). Obtained from Services:getResourceByName and passed to the calls that add or read a player's resources.
---@class ResourceType
local ResourceType = {}

---Returns the JSON key (mod-scoped identifier) of this entity.
---@return string
function ResourceType:getJsonKey() end

---The static game-content catalogue, bound to the global `LIBRARY`. Looks up artifacts, creatures, factions, hero classes/types, resources, secondary skills and spells by their config name (the same string used in JSON definitions).
---@class Services
local Services = {}

---Looks up an artifact by its JSON key. Returns nil if not found.
---@param name string # JSON key of the artifact (e.g. `core:goldenBow`).
---@return Artifact
function Services:getArtifactByName(name) end

---Looks up a creature by its JSON key. Returns nil if not found.
---@param name string # JSON key of the creature (e.g. `core:pikeman`).
---@return Creature
function Services:getCreatureByName(name) end

---Looks up a faction by its JSON key. Returns nil if not found.
---@param name string # JSON key of the faction (e.g. `core:castle`).
---@return Faction
function Services:getFactionByName(name) end

---Looks up a hero class by its JSON key. Returns nil if not found.
---@param name string # JSON key of the hero class (e.g. `core:knight`).
---@return HeroClass
function Services:getHeroClassByName(name) end

---Looks up a hero type by its JSON key. Returns nil if not found.
---@param name string # JSON key of the hero type (e.g. `core:orrin`).
---@return HeroType
function Services:getHeroTypeByName(name) end

---Looks up a resource by its JSON key. Returns nil if not found.
---@param name string # JSON key of the resource (e.g. `core:gold`).
---@return ResourceType
function Services:getResourceByName(name) end

---Looks up a spell by its JSON key. Returns nil if not found.
---@param name string # JSON key of the spell (e.g. `core:magicArrow`).
---@return Spell
function Services:getSpellByName(name) end

---Looks up a secondary skill by its JSON key. Returns nil if not found.
---@param name string # JSON key of the secondary skill (e.g. `core:wisdom`).
---@return Skill
function Services:getSecondarySkillByName(name) end

---Looks up a spell school by its JSON key. Returns nil if not found.
---@param name string # JSON key of the spell school (e.g. `core:fire`).
---@return SpellSchool
function Services:getSpellSchoolByName(name) end

---A secondary-skill definition (Wisdom, Tactics, Logistics, …). Database metadata; per-hero skill levels are read off HeroInstance.
---@class Skill
local Skill = {}

---Returns the JSON key (mod-scoped identifier) of this entity.
---@return string
function Skill:getJsonKey() end

---A spell definition (Fire Bolt, Slow, Town Portal, …). Identifies kind and metadata (schools, level). Cast resolution and per-cast state live on SpellMechanics.
---@class Spell
local Spell = {}

---Returns the JSON key (mod-scoped identifier) of this entity.
---@return string
function Spell:getJsonKey() end

---Returns the text ID of the spell name.
---@return string
function Spell:getNameTextID() end

---True if the spell can only be cast on the adventure map.
---@return boolean
function Spell:isAdventure() end

---True if the spell can only be cast during combat.
---@return boolean
function Spell:isCombat() end

---True if the spell is a creature's innate ability rather than a learnable spell.
---@return boolean
function Spell:isCreatureAbility() end

---True if the spell is classified as beneficial to its target.
---@return boolean
function Spell:isPositive() end

---True if the spell is classified as harmful to its target.
---@return boolean
function Spell:isNegative() end

---True if the spell is classified as neutral (neither positive nor negative).
---@return boolean
function Spell:isNeutral() end

---True if the spell deals direct damage.
---@return boolean
function Spell:isDamage() end

---True if the spell is offensive (damage / curse-type effects).
---@return boolean
function Spell:isOffensive() end

---True if the spell is marked as special (e.g. cannot be obtained from common sources).
---@return boolean
function Spell:isSpecial() end

---True if the spell's effect persists and can't be dispelled normally.
---@return boolean
function Spell:isPersistent() end

---True if the spell is magical in nature (as opposed to a non-magical ability).
---@return boolean
function Spell:isMagical() end

---Returns the mana cost of the spell at the requested skill level.
---@param skillLevel integer # Mastery level used to look up the cost (0=basic, up to 3=expert).
---@return integer
function Spell:getCost(skillLevel) end

---Returns the spell's base power before caster bonuses.
---@return integer
function Spell:getBasePower() end

---Returns the spell's per-level power bonus.
---@param skillLevel integer # Mastery level used to look up the power bonus (0=basic, up to 3=expert).
---@return integer
function Spell:getLevelPower(skillLevel) end

---Returns the list of magic schools the spell belongs to.
---@return SpellSchool[]
function Spell:getSchools() end

---Runs a raw damage amount through this spell's damage pipeline - the school bonuses of the actor's hero, and the target's resistances, vulnerabilities and immunities. Use it for abilities that damage as if they were this spell without actually casting it.
---@param battle Battle # Battle the damage is dealt in.
---@param actor Unit # Unit whose ability deals the damage. Its hero, if it has one, provides the caster bonuses.
---@param target Unit # Unit taking the damage, whose resistances and vulnerabilities apply.
---@param rawDamage integer # Damage before any of those modifiers.
---@return integer
function Spell:adjustDamage(battle, actor, target, rawDamage) end

---Per-cast spell context: which Spell is being cast, who is casting it, at what power and level. Lua spell scripts receive this as the entry point to their cast logic and consult it for caster identity, target validation, and damage formulas.
---@class SpellMechanics
local SpellMechanics = {}

---True if the spell mechanics classify this cast as a positive effect.
---@return boolean
function SpellMechanics:isPositive() end

---True if the spell mechanics classify this cast as a negative effect.
---@return boolean
function SpellMechanics:isNegative() end

---True if the spell only affects friendly or enemy targets (vs. anyone in range).
---@return boolean
function SpellMechanics:isSmart() end

---True if the spell targets all valid targets simultaneously.
---@return boolean
function SpellMechanics:isMassive() end

---True if the first selected target is always considered hit, ignoring magic resistance.
---@return boolean
function SpellMechanics:alwaysHitFirstTarget() end

---Returns true if the given target would resist this cast.
---@param target Unit # Unit whose resistance is being tested.
---@return boolean
function SpellMechanics:wouldResist(target) end

---Returns the effective mastery level used for the spell's magnitude.
---@return integer
function SpellMechanics:getEffectLevel() end

---Returns the effective mastery level used for the spell's range.
---@return integer
function SpellMechanics:getRangeLevel() end

---Returns the effective spell power applied to the magnitude calculation.
---@return integer
function SpellMechanics:getEffectPower() end

---Returns the effect duration in turns.
---@return integer
function SpellMechanics:getEffectDuration() end

---Returns the computed effect value (e.g. damage / health amount).
---@return integer
function SpellMechanics:getEffectValue() end

---Returns the player color of the caster.
---@return integer
function SpellMechanics:getCasterColor() end

---Returns the battle side of the caster.
---@return BattleSide
function SpellMechanics:getCasterSide() end

---Returns the hero performing the cast, or nil if cast by a unit.
---@return HeroInstance
function SpellMechanics:getHeroCaster() end

---Returns the unit performing the cast, or nil if cast by a hero.
---@return Unit
function SpellMechanics:getUnitCaster() end

---Returns the text ID of the caster's name.
---@return string
function SpellMechanics:getCasterNameTextID() end

---Returns the battle callback associated with this cast.
---@return Battle
function SpellMechanics:getBattle() end

---Returns the raw effect value before unit-specific adjustments.
---@param basePowerMultiplier integer # Multiplier applied to the spell's base power.
---@param levelPowerMultiplier integer # Multiplier applied to the per-level power bonus.
---@return integer
function SpellMechanics:calculateRawEffectValue(basePowerMultiplier, levelPowerMultiplier) end

---Applies any spell-specific bonus modifier and returns the resulting value.
---@param value integer # Base value to which spell-specific modifiers are applied. Use 0 for default
---@return integer
function SpellMechanics:applySpecificSpellBonus(value) end

---Applies the generic spell-damage bonus and returns the resulting value.
---@param value integer # Base value to which the bonus is applied. Use 0 for default.
---@param target Unit # Unit whose own bonuses are factored into the result.
---@return integer
function SpellMechanics:applySpellBonus(value, target) end

---True if the target is receptive (not immune) to the spell.
---@param target Unit # Unit whose receptivity is being checked.
---@return boolean
function SpellMechanics:isReceptive(target) end

---True if the given unit is owned by the same player as the caster.
---@param unit Unit # Unit whose ownership is being compared against the caster's.
---@return boolean
function SpellMechanics:ownerMatches(unit) end

---Returns the Spell being cast.
---@return Spell
function SpellMechanics:getSpell() end

---Applies all per-target adjustments to the raw effect value.
---@param target Unit # Unit against which per-target adjustments are computed.
---@return integer
function SpellMechanics:adjustEffectValue(target) end

---Picks the appropriate plural-form variant of a text ID for the given count and language.
---@param baseTextID string # Base text ID used as the lookup base.
---@param count integer # Count for which engine needs to select plural form.
---@return string
function SpellMechanics:getPluralFormTextID(baseTextID, count) end

---Configuration for a battlefield obstacle that scripts hand to ServerCallback `addObstacle`. Captures anchor position, owning spell, caster stats, behavior flags, presentation assets, and an obstacle hex footprint.
---@class SpellObstacleDescriptor
---@field pos BattleHex # Anchor BattleHex of the obstacle (its primary position). Usually located in bottom-left corner of the obstacle
---@field obstacleType ObstacleType # Obstacle category — usual, absolute, spell-created, moat. See the ObstacleType enum.
---@field spell Spell # Spell that created the obstacle. Used for dispel and damage-source attribution. Only for spell-created obstacles
---@field turnsRemaining integer # How many turns the obstacle persists. -1 means permanent for the battle.
---@field casterSpellPower integer # Spell power of the caster at the moment of creation; feeds damage formulas.
---@field spellLevel integer # Spell skill level (0–3) the obstacle was cast at.
---@field casterSide BattleSide # Which battle side cast it; relevant for native-visibility and friendly-fire rules.
---@field minimalDamage integer # Floor for the damage the obstacle inflicts on trigger.
---@field hidden boolean # If true, the obstacle is invisible to the opposing side until triggered.
---@field passable boolean # If true, units may step onto the obstacle's hexes (e.g. trap obstacles).
---@field trap boolean # If true, behaves as a trap: triggers on enter rather than blocking movement.
---@field removeOnTrigger boolean # If true, the obstacle disappears after being triggered once.
---@field nativeVisible boolean # If true, the caster's side always sees the obstacle even when `hidden` is set.
---@field trigger string # Script-side identifier of the trigger spell (looked up by the spell mechanics).
---@field appearSound string # Sound effect played when the obstacle appears.
---@field appearAnimation string # Animation played when the obstacle appears.
---@field animation string # Looping animation shown while the obstacle is on the battlefield.
---@field removalAnimation string # Animation played when the obstacle is removed (expires or is dispelled). Falls back to appearAnimation if empty.
---@field customSize BattleHex[] # Optional list of BattleHex values defining a multi-hex footprint.
local SpellObstacleDescriptor = {}

---Output accumulator passed to a spell's `canBeCast` / `canBeCastAt` check. Scripts append reasons the cast cannot proceed — generic, standard (picked from the ESpellCastProblem enum), or fully custom via MetaString. An empty SpellProblem means the cast is allowed.
---@class SpellProblem
local SpellProblem = {}

---Adds a custom-message problem entry built from the given MetaString config.
---@param config MetaString # MetaString that describes the custom problem message.
function SpellProblem:addCustom(config) end

---Adds the generic 'cannot cast' problem entry derived from the given mechanics.
---@param mechanics SpellMechanics # Mechanics of the spell being cast.
function SpellProblem:addGeneric(mechanics) end

---Adds a standard problem entry with the requested SpellCastProblem value.
---@param mechanics SpellMechanics # Mechanics of the spell being cast.
---@param spellProblem SpellCastProblem # Standard problem code to surface.
function SpellProblem:addStandard(mechanics, spellProblem) end

---A spell school (Fire, Water, Earth, Air, …). Identifies which school a spell belongs to and is used for school-based immunity and reduction checks.
---@class SpellSchool
local SpellSchool = {}

---Returns the JSON key (mod-scoped identifier) of this entity.
---@return string
function SpellSchool:getJsonKey() end

---Returns the text ID of the spell school name.
---@return string
function SpellSchool:getNameTextID() end

---A creature stack as it exists in an army outside of combat (hero slot, town garrison, or any other map object). Carries the creature type, current count, and any bonuses it contributes. For the battle-side view of the same stack, see Unit.
---@class StackInstance
local StackInstance = {}

---Returns the Creature type of the units in this stack.
---@return Creature
function StackInstance:getType() end

---Returns the number of creatures currently in this stack.
---@return integer
function StackInstance:getCount() end

---A town on the adventure map. Provides its owner and what has been built in it.
---@class TownInstance
local TownInstance = {}

---Returns the player color that owns this town, or the neutral player when it is unowned.
---@return integer
function TownInstance:getOwner() end

---Returns the buildings that have been built in this town, upgrades of other buildings among them.
---@return Building[] # Every building standing in this town.
function TownInstance:getBuildings() end

---Represents a creature stack participating in the current battle. Provides access to the live combat state — position, owner, current health, applied bonuses, ability checks. To stage modifications, copy into a UnitState, edit it, then commit via server.
---@class Unit
local Unit = {}

---Returns the bonuses of the bearer that match the filter. Say as much as the filter can express, since that is also what the engine can cache; narrow whatever is left with `BonusList:filter`.
---@param filter BonusFilter # Which bonuses to collect. An empty filter collects every one of them.
---@return BonusList # Bonuses of the bearer the filter describes.
function Unit:getBonuses(filter) end

---Returns what the matching bonuses are worth together. Not a plain sum - percentages, independent floors and ceilings combine by the rules of the engine. Prefer this over adding up `getBonuses` where possible.
---@param filter BonusFilter # Which bonuses to count. An empty filter counts every one of them.
---@return integer # Value of the matching bonuses taken together.
function Unit:getBonusesValue(filter) end

---True if the bearer carries a bonus the filter describes. Prefer this over testing the size of `getBonuses`, which hands the whole list over to the script to answer a question the engine can answer on its own.
---@param filter BonusFilter # Which bonuses to look for. An empty filter asks whether the bearer has any at all.
---@return boolean # True if the bearer carries at least one matching bonus.
function Unit:hasBonuses(filter) end

---Returns the minimum damage one creature in the stack will deal.
---@param ranged boolean # True for ranged attack value, false for melee.
---@return integer
function Unit:getMinDamage(ranged) end

---Returns the maximum damage one creature in the stack will deal.
---@param ranged boolean # True for ranged attack value, false for melee.
---@return integer
function Unit:getMaxDamage(ranged) end

---Returns the creature's attack stat.
---@param ranged boolean # True for ranged attack value, false for melee.
---@return integer
function Unit:getAttack(ranged) end

---Returns the creature's defense stat.
---@param ranged boolean # True for defense against ranged attacks, false for defense against melee.
---@return integer
function Unit:getDefense(ranged) end

---True if the stack has at least one alive creature.
---@return boolean
function Unit:isAlive() end

---True if this stack is a clone produced by a Clone spell.
---@return boolean
function Unit:isClone() end

---True if this stack has an alive clone summoned by a Clone spell.
---@return boolean
function Unit:hasClone() end

---True if the stack has no remaining alive creatures.
---@return boolean
function Unit:isDead() end

---True if the stack was completely removed from the battlefield including its corpse.
---@return boolean
function Unit:isGhost() end

---True if the stack can be targeted by spells / attacks.
---@param allowDead boolean # Pass true to count dead but resurrectable stacks as valid targets.
---@return boolean
function Unit:isValidTarget(allowDead) end

---True if the stack has invincibility (cannot be damaged or killed).
---@return boolean
function Unit:isInvincible() end

---True if the unit is absolutely immune to the given spell.
---@param spell Spell # Spell to test absolute immunity against.
---@return boolean
function Unit:hasAbsoluteImmunity(spell) end

---True if the stack was summoned during battle (e.g. by Summon Elementals).
---@return boolean
function Unit:isSummoned() end

---True if the stack is a living creature - not undead, not a golem-like non-living unit.
---@return boolean
function Unit:isLiving() end

---Returns the player color controlling this unit.
---@return integer
function Unit:getOwner() end

---Returns the army slot in the army this unit occupies. NOTE: All summoned units share the same slot
---@return integer
function Unit:getSlot() end

---Returns the battle side (attacker or defender) this unit belongs to.
---@return BattleSide
function Unit:getSide() end

---Returns the battlefield hex occupied by the unit, or front hex for double-wide units
---@return BattleHex
function Unit:getPosition() end

---Returns the total hit points across all creatures in the stack, including dead.
---@return integer
function Unit:getTotalHealth() end

---Returns the current hit points of living creatures of this unit.
---@return integer
function Unit:getAvailableHealth() end

---Returns the number of creatures currently alive in the stack.
---@return integer
function Unit:getCount() end

---Returns the health left of the first creature in the unit stack.
---@return integer
function Unit:getFirstHPleft() end

---True if the stack can shoot in general, even if out of ammo. See canShoot to check if unit can shoot right now.
---@return boolean
function Unit:isShooter() end

---True if the stack is one of the towers of a besieged town.
---@return boolean
function Unit:isTurret() end

---Which of the three towers of a besieged town this stack is.
---@return string? # "keep", "upper" or "lower"; nil when the stack is no tower.
function Unit:getTurretPart() end

---Returns the maximum hit points of a single creature in the stack.
---@return integer
function Unit:getMaxHealth() end

---True if the unit currently covers the given hex (accounts for double-wide creatures).
---@param position BattleHex # Battlefield hex to test against the unit's footprint.
---@return boolean
function Unit:coversPos(position) end

---Returns the Creature type of the units in this stack.
---@return Creature
function Unit:getCreature() end

---Returns the initial number of creatures this stack had at battle start.
---@return integer
function Unit:getBaseAmount() end

---Returns the list of hexes currently occupied by the unit.
---@return BattleHexArray
function Unit:getHexes() end

---Returns the hexes adjacent to the unit - six for a single-hex unit, eight for a double-wide one.
---@return BattleHexArray
function Unit:getSurroundingHexes() end

---Returns a copy of the unit's state allowing copying or changing this unit via server calls.
---@return UnitState
function Unit:copy() end

---Returns the creature level (1..7) of the unit's type.
---@return integer
function Unit:creatureLevel() end

---Returns the level of the stack itself, which for a commander is its own level rather than the tier of its creature. Use `creatureLevel` when the creature type is what matters.
---@return integer
function Unit:getLevel() end

---DEPRECATED. Returns the unit's internal numeric identifier.
---@return integer
function Unit:unitID() end

---Editable copy of a battle Unit. Obtained via `Unit:copy()`; scripts edit fields (position, defending, clone, summoned, …) and inflict damage locally, then hand the result to ServerCallback `changeUnit` or `addUnit` to broadcast the update through a battle pack.
---@class UnitState
local UnitState = {}

---Returns the minimum damage one creature will deal.
---@param ranged boolean # True for ranged attack value, false for melee.
---@return integer
function UnitState:getMinDamage(ranged) end

---Returns the maximum damage one creature will deal.
---@param ranged boolean # True for ranged attack value, false for melee.
---@return integer
function UnitState:getMaxDamage(ranged) end

---Returns the creature's attack stat.
---@param ranged boolean # True for ranged attack value, false for melee.
---@return integer
function UnitState:getAttack(ranged) end

---Returns the creature's defense stat.
---@param ranged boolean # True for defense against ranged attacks, false for defense against melee.
---@return integer
function UnitState:getDefense(ranged) end

---True if the stack has at least one alive creature.
---@return boolean
function UnitState:isAlive() end

---True if this stack is a clone produced by the Clone spell.
---@return boolean
function UnitState:isClone() end

---True if the stack has no remaining alive creatures.
---@return boolean
function UnitState:isDead() end

---True if the stack was completely removed from the battlefield including its corpse.
---@return boolean
function UnitState:isGhost() end

---True if the stack can be targeted.
---@param allowDead boolean # Pass true to count dead but resurrectable stacks as valid targets.
---@return boolean
function UnitState:isValidTarget(allowDead) end

---True if the stack has invincibility.
---@return boolean
function UnitState:isInvincible() end

---True if the stack was summoned during battle.
---@return boolean
function UnitState:isSummoned() end

---Returns the player color controlling this unit.
---@return integer
function UnitState:getOwner() end

---Returns the army slot in the army this unit occupies. NOTE: All summoned units share the same slot
---@return integer
function UnitState:getSlot() end

---Returns the battlefield hex occupied by the unit, or front hex for double-wide units
---@return BattleHex
function UnitState:getPosition() end

---Returns the total hit points across all creatures in the stack, including dead.
---@return integer
function UnitState:getTotalHealth() end

---Returns the current hit points of living creatures of this unit.
---@return integer
function UnitState:getAvailableHealth() end

---Returns the number of creatures currently alive in the stack.
---@return integer
function UnitState:getCount() end

---Returns the maximum hit points of a single creature.
---@return integer
function UnitState:getMaxHealth() end

---True if the unit currently covers the given hex.
---@param position BattleHex # Battlefield hex to test against the unit's footprint.
---@return boolean
function UnitState:coversPos(position) end

---Returns the initial number of creatures this stack had at battle start.
---@return integer
function UnitState:getBaseAmount() end

---True if the unit is absolutely immune to the given spell.
---@param spell Spell # Spell to test absolute immunity against.
---@return boolean
function UnitState:hasAbsoluteImmunity(spell) end

---Returns the Creature type of the units in this stack.
---@return Creature
function UnitState:getCreature() end

---Returns the list of hexes currently occupied by the unit.
---@return BattleHexArray
function UnitState:getHexes() end

---Sets whether unit has defended in this round.
---@param value boolean # New defending flag.
function UnitState:setDefending(value) end

---Marks the stack as a clone.
---@param value boolean # New cloned flag.
function UnitState:setCloned(value) end

---Marks that the unit has had drained mana from enemy hero this turn.
---@param value boolean # New drained-mana flag.
function UnitState:setDrainedMana(value) end

---Sets the feared status (skips the unit's current turn).
---@param value boolean # New feared flag — when true the unit will skip its next turn.
function UnitState:setFear(value) end

---Marks that the unit has already triggered a morale bonus this turn.
---@param value boolean # New had-morale flag.
function UnitState:setHadMorale(value) end

---Marks that the unit has cast a spell this turn.
---@param value boolean # New cast-spell-this-turn flag.
function UnitState:setCastSpellThisTurn(value) end

---Sets the ghost state removing them from the battle
---@param value boolean # New ghost flag — when true the unit becomes invisible to the battle.
function UnitState:setGhost(value) end

---Marks the unit as transitioning to the ghost state.
---@param value boolean # New ghost-pending flag.
function UnitState:setGhostPending(value) end

---Marks that the unit has moved this round.
---@param value boolean # New moved-this-round flag.
function UnitState:setMoved(value) end

---Marks the unit as summoned during combat.
---@param value boolean # New summoned flag.
function UnitState:setSummoned(value) end

---Marks that the unit is currently waiting.
---@param value boolean # New waiting flag.
function UnitState:setWaiting(value) end

---Marks that the unit has already used its wait this turn.
---@param value boolean # New waited-this-turn flag.
function UnitState:setWaitedThisTurn(value) end

---Moves the unit to the given hex.
---@param hex BattleHex # Destination hex for the unit.
function UnitState:setPosition(hex) end

---Links this stack to a clone unit produced by a Clone spell.
---@param unit Unit # Unit instance to register as this stack's clone.
function UnitState:setClone(unit) end

---Deals damage to the stack, clamped to available health.
---@param amount integer # Damage to apply; will be clamped to remaining health.
---@return integer # Damage value actually applied (may be less than requested if the stack was killed).
function UnitState:damage(amount) end

---Heals the stack. Returns the healed hit points and the resurrected creature count, if any.
---@param amount integer # Hit points to restore.
---@param level HealLevel # Heal tier (heal, resurrect, overheal).
---@param power HealPower # Persistence — one-battle vs permanent.
---@return integer, integer # Healed hit points, and the count of creatures resurrected (zero if none).
function UnitState:heal(amount, level, power) end

